### ISSUE TITLE
Create System.Device.Gpio Overview doc

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#100]
It would be beneficial to create a **System.Device.Gpio Overview** markdown to help newbies get started along with more technical details on infrastructure.  It could include the following topics:

**NOTE**: The intent of this overview is to focus on the following:
1. Intro examples of creating a protocol connection (e.g. I2C, SPI) and instantiating the respective device (e.g. I2cDevice, SpiDevice).  This would be more focused on how it relates to interface topics (e.g. buses, addressing, etc.);  not so much on particular binding.
2. Understanding how the OS and/or specific device is determined.
3. Understanding of external bindings.
4. Other topics?

⚠️  It might be more appropriate to document certain topics in [Microsoft Docs](https://docs.microsoft.com) to keep consistent with the overall .NET ecosystem.

- [ ] Create/add diagram helper showing the structure along with sections for future work.
- [ ] Add System.Device.Gpio API folder and placeholder markdown files under [Documentation](https://github.com/dotnet/iot/tree/master/Documentation).
- [ ] Update [Documentation](https://github.com/dotnet/iot/tree/master/Documentation) with other types of interfaces.
- [ ] Update [Documentation System.Device.* APIs section](https://github.com/dotnet/iot/tree/master/Documentation#systemdevice-apis) with link to System.Device.Gpio API README markdown.
- [ ] Add link to System.Device.Gpio API README in [main repo README markdown](https://github.com/dotnet/iot/blob/master/README.md).

**Comment by shaggygi** [comment]
@joperezr @joshfree another one you can assign to me.  I have some early thoughts started for this.  The plan is to have multiple PRs over time since this will cover lots of material and changes are needed as progress is made on API.

If possible, the idea is to stub out beginning markdowns and such with the intent to add content as time allows.  I'll try to add some action items above while reviewing.

**Comment by joperezr** [comment]
I'm not sure of concrete workitems that can come out of this. I know that you logged this some time ago and a bunch of changes to documentation have happened since, do you think this is still an issue? Is there a specific thing we should add to our existing docs?

**Comment by shaggygi** [comment]
I was originally thinking it would be good to have an overall doc that explained the basics down to more technical detail.  Sort of explaining with diagrams and such for peeps to understand structure of things like device/controller and how it fits with with the different OS/hardware boards.  I'm not sure the best format (markdown, slides, etc.), but the dust needs to settle (new talks of controllers, etc. before attempting to do so.

This is more of a "nice to have" than a real need since we're getting more tidbits throughout the repo.  We can close and maybe circle back one day.

**Comment by joperezr** [comment]
I see, ok that makes sense. We don't need to close it, issues don't have to mean that it is a problem we need to fix right away, so it's fine to keep it open I just wanted to make sure that all of the documentation changes that we have been working on had not already covered this.

**Comment by krwq** [comment]
Marking as 3.0 for now since we should improve some docs until then but we may reiterate on that later as I'm not sure if we will be able to fully address all requests from this issue

**Comment by joperezr** [comment]
@shaggygi I'm finally back from my leave, and I know that you have made some changes in the past on our documentation, is the above list still accurate? (meaning that we haven't checked any of those boxes yet?)

**Comment by shaggygi** [comment]
@joperezr i think it is semi-accurate still.  I’m thinking it might be better to approach this with slides instead of markdown.  That would allow others to possibly show with different audiences.  Since the API is still young and discussions are still trying to determine interfaces and such, I’d say this can wait until after.  Maybe close and we can circle back later?

Good to hear you’re back.  I’ve been (still am) out with an injury that’s hinder coding.

**Comment by joperezr** [comment]
I see, instead of closing I'll just flag it as future, so that we continue to track the work. Sad to hear about your injury, hope you get well soon!

**Comment by krwq** [comment]
@joperezr moving back to 3.0 since we closed the other issue. We should at min add `How to start` to move this to Future I think

**Comment by joperezr** [comment]
Sounds good to me.

**Comment by RheaAyase** [comment]
> Add link to System.Device.Gpio API README in main repo README markdown.

Information about contributing and building the project should be in CONTRIBUTING.md - it gets nicely popped out in front of everyone's face when they click "create pull request," etc...

**Comment by shaggygi** [comment]
Do you think this type of documentation should be in this repo or added under an 'IoT' section located with [other .NET topics](https://docs.microsoft.com)?  If so, we might want to ping the docs team to possibly offer guidance on how we structure/document the different features/topics within **System.Device.***.

**Comment by krwq** [comment]
I'd start wth README.md file and after we ship and APIs become stable then we should request docs team to have that.

**Comment by krwq** [comment]
We have just added PR and issue templates to improve state a bit. Please let us know if you think there should be more/less links/info (or even better send PR with changeset).
