### ISSUE TITLE
Create a markdown how to create a Publish Profile

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#103]
It would be nice to have some better docs explaining how to quickly add a publish profile.

This Channel9 video ([Have Your Pi and Eat It Too: .NET Core 2.1 on Raspberry Pi](https://channel9.msdn.com/Events/dotnetConf/2018/S314)) explains some detail that helps.

Add this to [Documentation](https://github.com/dotnet/iot/tree/master/Documentation) markdown section.

Assign to me if desired.

**Comment by joperezr** [comment]
Is the idea of this markdown to explain how to publish an app for a raspberry pi when building on a development box?

**Comment by shaggygi** [comment]
Yes,  The thinking is to have a basic doc explaining the steps, XML and such.
