### ISSUE TITLE
Switch samples to PackageRef

### ISSUE THREAD

**Issue by richlander** [dotnet/iot#1068]
The samples in this repo use project references, instead of PackageReference to the NuGet packages (that the repo produces) on NuGet.org. This has two (related) problems:

- The projects can only be built as-is within the repo.
- The projects do not demonstrate the best-practice for customer usage. For example, the packages they would need are not even listed in a comment in the projects.

Examples:

- https://github.com/dotnet/iot/blob/master/samples/led-blink/led-blink.csproj
- https://github.com/dotnet/iot/blob/master/samples/force-sensitive-resistor/force-sensitive-resistor.csproj

**Comment by richlander** [comment]
I added a proposal for how to handle this in #1069.

**Comment by joperezr** [comment]
We can totally do this but we have to be aware of the trade-offs. This would mean that if we make a breaking change on either the main library(not very likely) or a binding the sample uses (somewhat likely) then we would have issues like:
- Passing CI when making the breaking change but then getting a broken CI on the next build when we consume the new packages with the changes. This in case we exclusively use package reference on samples.
- Failing CI when making the breaking changes so we adjust the samples on the same PR, but if people grab the project and paste it outside the repo it would just be broken as the package ref wouldn't satisfy the code. This in case we use your proposal.

Also one question, would we do this to only depend on packages from NuGet.org? If so, those get updated even less often than daily ones so problems might accumulate and samples might fall out of date. I'm not saying we shouldn't do it, I just want to mention the trade-offs we would see.

**Comment by richlander** [comment]
Resolved in https://github.com/dotnet/iot/pull/1069
