### ISSUE TITLE
SHT1x support

### ISSUE THREAD

**Issue by frogcrush** [dotnet/iot#1078]
Currently there is support for the SHT3x sensors. However, there is no support for the older SHT1x sensors which are still widely available for purchase. I would like to add support for the SHT1x line of devices, either by modifying the existing SHT3x code or by using that code as a basis.

![image](https://user-images.githubusercontent.com/6116333/82109830-05170900-96ee-11ea-8882-903526589ee2.png)

Datasheet: https://www.sparkfun.com/datasheets/Sensors/SHT1x_datasheet.pdf

**Comment by frogcrush** [comment]
Datasheet: https://www.sparkfun.com/datasheets/Sensors/SHT1x_datasheet.pdf

**Comment by pgrawehr** [comment]
Probably related: #1067

**Comment by frogcrush** [comment]
This is in-progress in #1080

**Comment by Ellerbach** [comment]
[Triage] On PR #1080, there is most likely a rebase to do and very little efforts to move this one forward. Up to grab!

**Comment by krwq** [comment]
[Triage] We're not tracking binding requests. If there is anything to discuss please re-open.
