### ISSUE TITLE
Is there a need to implement 74595 drivers?

### ISSUE THREAD

**Issue by HumJ0218** [dotnet/iot#1085]
In some devices there are not enough GPIO lines

74595s can be a output-only GPIO driver:

SPI > 595 - 595 - ...
GPIO > 0 1 2 3 4 5 6 7 8 9 10 11 ...

So we can use SPI to drive devices with parallel data lines (ex. HD44780 the LCD screen)

**Comment by pgrawehr** [comment]
Please specify the exact type of chip you mean and ideally provide a link to the data sheet. 

We do have support for the MCP23xxx GPIO expanders, they should do what you want. They have 8 or 16 configurable input/output pins. The MCP23S17 is for SPI, the MCP32017 for I2C.
