### ISSUE TITLE
Starting PWM output with WinRT APIs requires extra call to ChangeDutyCycle()

### ISSUE THREAD

**Issue by anphel31** [dotnet/iot#109]
Enabling PWM output in Windows IoT core on Hummingboard requires an extra call to ChangeDutyCycle() after the PWM pin's Start() function is called.
See #97

**Comment by joperezr** [comment]
Is the idea of this issue to track the work of removing the extra call once the WinRT Apis are fixed? Is there an actual plan to fix the WinRT Apis so this extra call is not longer required?

**Comment by krwq** [comment]
@anphel31 should the issue be closed now since the PR is merged?

**Comment by joshfree** [comment]
Fixed by #97

**Comment by joperezr** [comment]
I think the idea of this issue was to track the removal of that extra call once WinRT APIs got fixed so we wouldn’t need it any longer.
