### ISSUE TITLE
Request a way to keep the camera open in VideoDevice

### ISSUE THREAD

**Issue by HumJ0218** [dotnet/iot#1093]
There are many cameras that grab pictures immediately after initialization, and there will be an unstable picture situation, ex. a full-green or black frame.

How about adding a method to keep the camera open. So users can make a delay before capture a image to avoid the green frame?

@ZhangGaoxing

**Comment by krwq** [comment]
I wouldn't mind if camera stayed open for whole lifetime of the class

**Comment by HumJ0218** [comment]
@krwq Thank you for your explanation. My understanding is that the ABCDE five lines are inputs from a 5-32 decoder to select the current pixel line. I have this doubt because I bought a 128x64 RGB LED screen with a label `HUB75` besides interface and only have ABC three lines as line selection lines. After some research I found that these three lines are inputs of a group of shift registers. The outputs lead the pixel lines.

My question is whether there are multiple HUB75 implementations, and they are not compatible with each other.

**Comment by krwq** [comment]
I'm not sure - I suspect people implement everything specially for their devices and once they get it to work they just don't care about making it compatible with other versions (unless they have both)

**Comment by Ellerbach** [comment]
@HumJ0218 , did you have a chance to look at the PR #1163? 
This should solve your issue. Please let us know so we can work on the PR and merge it. Let me know if you need any help.

**Comment by HumJ0218** [comment]
@Ellerbach OK. I'll try it on weekend

**Comment by Ellerbach** [comment]
[Triage] Regarding the request and the PR #1163, this seems to be addressed.
