### ISSUE TITLE
PiJuice UPS Implementation

### ISSUE THREAD

**Issue by DazFahy** [dotnet/iot#1096]
I currently have a C# .NET Standard library [(based on)](https://github.com/tresoft/PiJuice-Uwp) which I developed for the [PiJuice](https://github.com/PiSupply/PiJuice).

I was wondering if it would be of any use in the Iot.Device.Bindings project, or is it to specific because it is a Raspberry Pi only HAT?

**Comment by Ellerbach** [comment]
We do have various hats specific to Raspberry supported: GrovePi, GoPiGo3, BrickPi3 and few more. 
IT can be interesting of course to get a UPS, it will be the first one. We had discussions with @krwq on adding some support for System Management Bus which is about power management. 
So looking forward at your PR 😊 That may raise few discussions on what we may generalize from your work.
