### ISSUE TITLE
Enable Debug.WriteLine to write to a connected LED panel

### ISSUE THREAD

**Issue by richlander** [dotnet/iot#11]
I am thinking about a way of redirecting Debug.WriteLine to a different location or screen.

Imagine scrolling text from Debug.WriteLine being shown on one of these: https://www.adafruit.com/product/3527

**Comment by krwq** [comment]
To fix this we need:
- abstraction for Display
- logging infrastructure so that you can plug in that easily
- perhaps helper class to make it easier

**Comment by Ellerbach** [comment]
[Triage] With the logger class we can now output anywhere it's supported the logging. Closing this issue.
