### ISSUE TITLE
Enable opening multiple pins in one call

### ISSUE THREAD

**Issue by richlander** [dotnet/iot#1108]
In almost all my implementation, I end up writing this code.

```csharp
            foreach (var pin in _pins)
            {
                _controller.OpenPin(pin, PinMode.Output);
            }
```

I'd like to see something like this (copied from an extension method I wrote; doesn't have to be an extension method): 

```csharp
    public static void OpenPins(this GpioController controller, PinMode mode, params int[] pins)
    {
        foreach (var pin in pins)
        {
            controller.OpenPin(pin, mode);
        }
    }
```

**Comment by Ellerbach** [comment]
[Triage] It is a very convenient method that would perfectly fit in an extension if you need it. So far, it feels like adding something that will not be used a lot.
