### ISSUE TITLE
dht -11 can't work

### ISSUE THREAD

**Issue by jackswei** [dotnet/iot#1112]
**Describe the bug**

OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /opt/dotnet/sdk/3.1.300/

i use 1-Wire Protocol

https://github.com/dotnet/iot/blob/master/src/devices/Dhtxx/README.md

it show 
NaN ,
NaN

**Comment by pgrawehr** [comment]
Please show us the code you use. The Dht11 does not use the "normal" 1-wire-protocol. We therefore have a special binding for Dht11.
