### ISSUE TITLE
Provide APIs from WIndows IoT Extensions as .NET Core

### ISSUE THREAD

**Issue by ddobric** [dotnet/iot#1117]
To enable .NET Core to be platform, which run on any device, it is necessary to provide support for diverse IoT scenarios.

For example, we already have a set of APIs related to BLE, various sensors and GPIO. They all are implemented as a part of Windows IoT Extensions and unfortunately available for UWP only.
How about implementing them as native .NET Core API and integrating them as standard ?

#See also: https://github.com/dotnet/standard/issues/358

**Comment by joperezr** [comment]
Given this was open a long time ago and since then we actually added the dotnet/iot repo where we have a lot of iot APIs implemented already I'll go ahead and close this. @ddobric if you have some concrete APIs you want implemented which are not already present in this repo feel free to reopen.
