### ISSUE TITLE
It is not possible to display custom character created via CustomCharacter on the Lcd1602

### ISSUE THREAD

**Issue by R10Rasmus** [dotnet/iot#1118]
In the Lcd1602 it is not not possible to to display custom character created via CustomCharacter. In fx. pyton RPLCD.gpio thay can be display via the write met ode. But in Lcd1602 the write met ode only support an text or a ReadOnlySpan<byte>, not the location of the custom character.

**Comment by pgrawehr** [comment]
This is supported. See the example code, which has a nice example with a walking man.

**Comment by R10Rasmus** [comment]
the examples is written for Hd44780. I can be written to work with Lcd1602. Can we move the example to CharacterLcd.Sample ?

**Comment by pgrawehr** [comment]
The Hd44780 is the chip that drives the LCD1602 or 2004. The extended examples should work just fine with your display.

**Comment by R10Rasmus** [comment]
okay thanks
