### ISSUE TITLE
The Lcd1602 do not wrap text to next line if it hit the end of the line

### ISSUE THREAD

**Issue by R10Rasmus** [dotnet/iot#1120]
On the Lcd1602 the text do not wrap after 16 characters, it dos it after 25 characters. And if it reach the end of line 2, it do not start back at first position on line 1.

**Comment by pgrawehr** [comment]
That's expected behavior of the low level interface. Use `LcdConsole` to get a high-level abstraction that does automatic line feeding (if desired).

**Comment by R10Rasmus** [comment]
It is true it warps via LcdConsole
