### ISSUE TITLE
Uln2003 - wrong time of steps

### ISSUE THREAD

**Issue by wsad4ryba** [dotnet/iot#1133]
**Describe the bug**
The time of step (_stepMicrosecondsDelay) has one little mistake. The variable _steps is used to calculate the delay. Therefore, the delay is calculated well only for _steps equal to full revolutions.

**Steps to reproduce**
Try to set RPM to 1, and do only one step.
```csharp
Uln2003 motor = new Uln2003(bluePin, pinkPin, yellowPin, orangePin)
motor.RPM = 1;
motor.Step(1);
```
No motor or driver is needed to see this error, just check the execution time of the function.

**Expected behavior**
One step should take about 15ms (half step = 60000/4096) or 30ms (full step = 60000/2048).

**Actual behavior**
Regardless of the value of the steps passed to the step function, the execution time for RPM = 1 will be one minute

**Versions used**
Cloned repository

**Possible solution**
Add a new variable with number of steps required to full rotation?
![steps_fix](https://user-images.githubusercontent.com/61989452/87072495-23940f00-c21c-11ea-8264-0c7d89d2e6b3.PNG)

I'm new to C # and github so forgive me if the description doesn't match the standards.

**Comment by krwq** [comment]
Thanks for reporting, do you feel like sending a patch?
