### ISSUE TITLE
Enable Policheck as part of build pipeline

### ISSUE THREAD

**Issue by ericstj** [dotnet/iot#1146]
We should run Policheck on the IOT repo and fix up the things it flags.  @Anipik has the info on how to set this up.  It's semi-automated by arcade infra.

**Comment by Anipik** [comment]
I can help set this up but do we want it to be part of our official builds ? we stopped doing that for the runtime repo and just run those as a part of the nightly builds and release pipeline

**Comment by ericstj** [comment]
@Anipik same behavior as dotnet/runtime should be fine.  cc @joperezr @krwq
