### ISSUE TITLE
Pololu Maestro

### ISSUE THREAD

**Issue by AngeloBestetti** [dotnet/iot#1149]
Pololu Maestro Support

https://www.pololu.com/product/1357

**Comment by shaggygi** [comment]
@AngeloBestetti link routes back to GitHub.

**Comment by Ellerbach** [comment]
@AngeloBestetti , fixed the URL. 
@AngeloBestetti , can you please describe a bit your use case? 
I had a quick look at the protocole, it's using serial port, quite simple and straight forward. So far, we don't have at all this hardware to implement and test. And not the time to implement it in the short future. Keeping it for the future.

**Comment by krwq** [comment]
[Triage] we're not tracking binding requests, if there are any questions which need discussion please reopen
