### ISSUE TITLE
Should .editorconfig file be added to repo

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#115]
Since this repo is following the [coding standards](https://github.com/dotnet/iot/issues/64#issuecomment-444939481) similar to [dotnet/corefx](https://github.com/dotnet/corefx), would it be possible to add the same **[.editorconfig](https://github.com/dotnet/corefx/blob/master/.editorconfig)** file to this repo?

**Comment by joperezr** [comment]
Yes we totally should 😄 Feel free to throw in a PR for this
