### ISSUE TITLE
Wrong temperature calculation for DHT21 and derived devices

### ISSUE THREAD

**Issue by fehdem** [dotnet/iot#1161]
The calculation of the temperature seems to be wrong. It is encoded in two bytes, according to the datasheet.
The current calculation is:
https://github.com/dotnet/iot/blob/21cf491456542716ff69192cb9f50da7e0dc2f58/src/devices/Dhtxx/Devices/Dht21.cs#L34

I think it should be corrected like this: `(((readBuff[2] & 0x7F) << 8) | readBuff[3]) * 0.1;`

**Comment by Ellerbach** [comment]
Related to #1153
And yes, seems that there is an issue. See the other thread.
