### ISSUE TITLE
Hcsr04 should use UnitsNet 

### ISSUE THREAD

**Issue by Ellerbach** [dotnet/iot#1180]
**Describe the bug**

```Distance``` property returns a double which is actually coded as "cm". This should definitely use UnitsNet
https://github.com/dotnet/iot/blob/3c4034781d158b26be0bc4866c34192d86bc4ef1/src/devices/Hcsr04/Hcsr04.cs#L28

**Expected behavior**

Regarding the new rules for units, this should use the UnitsNet corresponding to meters

**Versions used**

Latest from the repo

**Comment by krwq** [comment]
we should fix it in this release

**Comment by Ellerbach** [comment]
This is now resolved by the merged PR
