### ISSUE TITLE
Sample: Display IP address on device startup

### ISSUE THREAD

**Issue by richlander** [dotnet/iot#12]
Many people want a way of determining a device IP address for an otherwise headless device. This info would need to be shown at device startup. By definition, there isn't a way to find out the IP address to start the program manually in this scenario.

We should build a sample that does this.

This would be the perfect LCD panel to use: https://www.adafruit.com/product/3527

**Comment by shaggygi** [comment]
@joshfree I would be interested in this.  Mainly to build up knowledge on in developing bindings.  I actually have hardware on order.  However, I am working on a simpler binding I want to finish up first.  Trying to get up-to-speed on related tooling (fritzing, etc.) and core APIs first.

**Comment by shaggygi** [comment]
@joshfree I have not forgot about this, but wanted to focus on testing the waters with [MCP23XXX binding](https://github.com/dotnet/iot/issues/88) first.

**Comment by shaggygi** [comment]
Referencing #178 as it was derived while working on this issue.

**Comment by shaggygi** [comment]
Referencing #188

**Comment by krwq** [comment]
I'm not sure I understand this issue. Currently Raspbian prints the IP on the console when booting and that can be read using serial ports using UART pins which are enabled by default.

Other thing is that you can modify the raspbian image before sending it to your SD card and add a script which broadcast the IP and ID to some server (that's what I currently do at home and can share that if anyone is interested)

**Comment by shaggygi** [comment]
@krwq i think i agree with you and this was more of a "wish list" item to show working while using the core API and a device.  I now have the [Ssd1306 binding](https://github.com/dotnet/iot/tree/master/src/devices/Ssd1306) with an example of displaying the RPi IP address.

If you add the steps how to execute an app on startup (#13), then I would be content on closing this one.  I wonder if a basic markdown would be worth adding for both Linux & Windows 10 IoT and linking under the Documentation section?

**Comment by krwq** [comment]
I can do brief explanation for linux, haven't played with Win IoT Core yet too much

**Comment by krwq** [comment]
@shaggygi instructions added - do we want to keep the issue?

**Comment by shaggygi** [comment]
I think the pieces delivered are what @richlander asked for.  I'd say go ahead and close.  Thx

**Comment by krwq** [comment]
@richlander please reopen if you think this is not addressed
