### ISSUE TITLE
Adding the library for ADS1256

### ISSUE THREAD

**Issue by onurgokyildiz** [dotnet/iot#1220]
8-Ch Delta-Sigma ADC With PGA for Factory Automation and Process Control
https://www.ti.com/product/ADS1256

**Comment by Ellerbach** [comment]
[Triage] This is up to grab for anyone having this device!

**Comment by krwq** [comment]
[Triage] We do not keep track of device bindings request. If anyone is interested in contributing or have anything to discuss please re-open or re-create.
