### ISSUE TITLE
Are there any exchange C# forums?

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/iot#1233]
Many people will answer the question here. I don't have a good C# exchange forum in China. Do you know what kind of active forum is in the United States? I want to learn about it recently. For example, C# memory directly accesses DMA

**Comment by frogcrush** [comment]
Here is a great list: https://dotnet.microsoft.com/platform/community

**Comment by Ellerbach** [comment]
[Triage] There are quite a lot of forums existing, like the one referenced before. You can as well use StackOverflow for example.
For specific questions about .NET IoT, you can use our [Discord channel](https://discord.gg/kqWhBbj) for example.
