### ISSUE TITLE
SenseHat sample throws runtime exceptions related to formatting

### ISSUE THREAD

**Issue by CamSoper** [dotnet/iot#1248]
I'm currently writing a quickstart that uses this sample, but it's currently broken due to formatting exceptions at runtime.

I've already fixed it locally, but the file the fix is in is getting renamed in https://github.com/dotnet/iot/pull/1243 so I'm going to wait until that's merged before I submit a PR so as not to create a merge issue.

**Comment by joperezr** [comment]
Thanks so much for finding it out and for contributing back the fix! The PR should get merged soon (today or tomorrow) so you should be unblocked to send a PR by then.
