### ISSUE TITLE
I2C API should support Restart/Repeat condition

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#129]
It appears you currently can only read and write using I2C API where it provides a Start/Stop at beginning and end of command.  Many I2C components will work by writing the address with a Write command and then follow with a ReadByte() or Read() for multiples.  However, there are components that require a Reset condition between writing and reading.

@bigdnf mentioned this in https://github.com/dotnet/iot/issues/111

Windows.Devices.I2c appears to have related support with a WriteRead():
https://docs.microsoft.com/en-us/uwp/api/windows.devices.i2c.i2cdevice.writeread#Windows_Devices_I2c_I2cDevice_WriteRead_System_Byte___System_Byte___

It appears the `UnixI2cDevice` has some started work [here](https://github.com/dotnet/iot/blob/0bb80590d409b0c974b4012c484828d7593268bc/src/System.Device.Gpio/System/Device/I2c/Drivers/UnixI2cDevice.Linux.cs#L59).  Have not found anything public to use similar to SPI [TransferFullDuplex](https://github.com/dotnet/iot/blob/0bb80590d409b0c974b4012c484828d7593268bc/src/System.Device.Gpio/System/Device/Spi/SpiDevice.cs#L14).

**Couple Linux references**
* https://stackoverflow.com/questions/35078131/why-repeated-start-based-i2c-operation-are-not-supported-in-linux
* https://stackoverflow.com/questions/505023/reading-writing-from-using-i2c-on-linux

**Comment by shaggygi** [comment]
I was tinkering with this for a little bit and was able to get the Restart bit to occur between write/read buffers.  I'm just not so sure on the best solution as devices can required different sequences of this.  For example, You might have to write a few bytes for addressing, followed by a Restart bit, write another for a command and then remaining data can be clocked in to read buffer.  One question is how can this be structured to allow multiple types of bits in specific locations of command? 🤔 

I'm putting these notes here to ponder later.

Added to I2cDevice.cs:
``` public abstract void WriteRead(Span<byte> writeBuffer, Span<byte> readBuffer);```

Added to UnixI2cDevice.Linux.cs:
```csharp
public override unsafe void WriteRead(Span<byte> writeBuffer, Span<byte> readBuffer)
{
  Initialize();

  fixed (byte* writeBufferPointer = writeBuffer)
  {
    fixed (byte* readBufferPointer = readBuffer)
    {
      Transfer(writeBufferPointer, readBufferPointer, writeBuffer.Length, readBuffer.Length);
    }
  }
}
```

**Comment by joperezr** [comment]
I think we can add the WriteRead method, but individual device bindings should still have to think about the specific protocol they require (meaining the Restart bit that you mention above) since that can't really be generalized. I would expect each binding to have all of that logic in their source code, and then call either Write(), Read() or WriteRead() methods as appropriate.

**Comment by joperezr** [comment]
Next steps for this:  We would need a formal Api proposal for this in order to consider adding it to the library, so feel free to submit one.

**Comment by shaggygi** [comment]
Just to note, all the bindings I've worked with appear to work by setting register pointer using a Write first and then follow up with the Reads.  So it hasn't hindered me so far.  Most of the device datasheets have diagrams on the steps to perform where a few had some more complex steps to do things like sequential writes/reads (and for more than one cycle of Writes/Reads within one command).

I also came across a note in a random blog that stated they had devices that would only work using the Reset condition and extra steps to configure the RPi.  They were not using .NET IoT, didn't provide the device names, so I couldn't confirm their accuracy.

I was able to produce the Reset condition with above code, but needs to be thought through more.  I'm okay with keeping this issue open for a period to allow others to chime in and keep record on possible devices that require this scenario. Investigate further if popular or close if not.

Thx

**Comment by ZhangGaoxing** [comment]
Hope to be implemented in the master branch as soon as possible. 
I have encountered problems in adding KT0803L binding recently. This is not the only one. When I used the old version **System.Devices.Gpio** package, it contained ReadWrite(), and MLX90614 worked well. However, Write()Read() mode does not work correctly when using the current **System.Device.Gpio** package.
@shaggygi @joperezr @krwq

**Comment by joperezr** [comment]
Adding `WriteRead` sounds reasonable to me. @ZhangGaoxing do you want to put up a PR for it?

**Comment by ZhangGaoxing** [comment]
@joperezr Let you do it. I'm not familiar with Linux drivers.😀

**Comment by ZhangGaoxing** [comment]
add two work incorrectly sequence diagrams
![1](https://user-images.githubusercontent.com/15957347/53154852-a6e89c80-35f6-11e9-9d28-ac80fa25161f.jpg)
![2](https://user-images.githubusercontent.com/15957347/53154856-a819c980-35f6-11e9-9884-0ef614d11352.jpg)

**Comment by krwq** [comment]
Marking as 3.0 since this is potentially blocking adding new devices

**Comment by ZhangGaoxing** [comment]
I think we should try to solve this problem as soon as possible. I found that the `SMBus protocol` devices I tried to bind were not working properly (I can't guarantee all the devices), like `MLX90614` (this sensor adafruit is on sale). I don't know if the latest version of the Raspberry Pi driver supports I2C Repeated Start, I refered this [post](https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=15840&sid=8c2fff5ce4395676800b4587f2a71b4e&start=25) to back the I2C driver, then I realized that our lib didn't provide WriteRead() method...

I remember that a long time ago version of `System.Devices.Gpio` provided this method.🤔
