### ISSUE TITLE
Ensure SPI's DataFlow.Lsb works

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#1308]
Per https://github.com/dotnet/iot/pull/1306#discussion_r529242750

SPI's DataFlow.Lsb might not be working on Raspberry PI. We should double check we use driver correctly and if driver doesn't support it we should reverse bits in software.

Once this work is done we should enforce this mode in PN532 and ensure it still works

**Comment by Ellerbach** [comment]
[Triage] Still on the radar, all elements available in the PN532 implementation. Still some work to do to move that into the driver and have this working across all SPI drivers. Btw, this can be used on one and the other, so if Lsb or Msb is not working, this trick can be applied.
