### ISSUE TITLE
Automate update work

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#1322]
Currently creating new package version of our repo takes couple of steps and some of them can be automated:
- regenerate device listing (`dotnet run` on https://github.com/dotnet/iot/tree/master/tools/device-listing and fix all warnings)
  - this always requires manual review
- ensure all desired code changes are merged
- ideally until done do not merge any new PRs (technically not required but will avoid confusion and accidental errors)
- [Internal] Create new package
  - Go to https://dev.azure.com/dnceng/internal/_build?definitionId=239
  - Select "Run Pipeline", select row which says variables and add new one: DotNetFinalVersionKind=release (no quotes anywhere)
  - Run and wait for it to finish
  - Once it is done and passes go to the artifacts section of the build, and find an artifact called 'Built packages' and from there download the two stable packages
  - Validate the package (double check version, check there are no unintentional changes)
- push package to nuget
- add git tag (`git tag -a <version> <commit_hash>`) and push it (`git push origin <version>`); `<version>` is i.e. `1.3`
- edit release notes on github (i.e. https://github.com/dotnet/iot/releases/tag/1.2), for list of commits between release use i.e.: https://github.com/dotnet/iot/compare/1.1...1.2
- after shipping create PR similar to https://github.com/dotnet/iot/pull/1310 to prepare for next release
  - this could be automated to tool having: `--update-minor`, `--update-major` or just `--version`
- wait for dependabot to create dependencies update PR (similar to: [System.Device.Gpio](https://github.com/dotnet/iot/pulls?q=is%3Apr+Bump+System.Device.Gpio+is%3Aclosed+author%3Aapp%2Fdependabot); [Iot.Device.Bindings](https://github.com/dotnet/iot/pulls?q=is%3Apr+Bump+Iot.Device.Bindings+is%3Aclosed+author%3Aapp%2Fdependabot))
- update the docs

cc: @joperezr

**Comment by joperezr** [comment]
We could add something to the build scripts that automate 1 and 3, for 2 nuget already has a single command line that can push packages to nuget.org that you need to pass credentials too. Given only a few have permissions to do so, I think it is better to follow the UI publish as it lets you validate and preview things before pushing (which is a non-reversible action)

**Comment by krwq** [comment]
@joperezr let's start with automating 1 and 3, for number 2 I think it is still worth to push it automatically, the reason is that we would like to eventually push more frequently and manual work will be a bit of a hassle. We can test it on myget first

**Comment by pgrawehr** [comment]
I think for 3, dependabot will create only one PR when there's a single place where the version of a specific package is mentioned. We should move all package versions that we use to `/eng/Versions.props`.

**Comment by Ellerbach** [comment]
[Triage] Thanks @krwq for volunteering in turning this as documentation :-)

**Comment by krwq** [comment]
This thread will be replaced by https://github.com/dotnet/iot/pull/1443
