### ISSUE TITLE
Open and build projects in public version of Visual Studio (not the Preview version)

### ISSUE THREAD

**Issue by SongweiFu-ITEM** [dotnet/iot#1330]
Now the projects can only be loaded and built in Visual Studio Preview version. 
It would be nice to be able to load projects from Visual Studio 2019 (community / professional / Enterprise).

**Comment by krwq** [comment]
cc: @joperezr

**Comment by joperezr** [comment]
This should theoretically work as long as you have the .net 5.0 installed globally in your machine. I'll take a look to see if that is not the case.

**Comment by SongweiFu-ITEM** [comment]
update from 16.5.4 to 16.8.2 solves the problem. no problem of loading the project from VS 2019.

**Comment by pgrawehr** [comment]
Yes, updating to at least 16.8.0 is required to build with the final .NET 5.0 version.

**Comment by Ellerbach** [comment]
So I guess this can be closed! Feel free to reopen if any other issue.
