### ISSUE TITLE
PiJuice returns wrong reading in some cases

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#1333]
Created based on @jstoker comment:
https://github.com/dotnet/iot/pull/1213#discussion_r531118940

Per comment GetBatteryCurrent and GetIOCurrent double convert negative numbers resulting in a value 1<<16 less than expected
https://github.com/dotnet/iot/blob/master/src/devices/PiJuice/PiJuiceStatus.cs#L147-L150

cc: @DazFahy

**Comment by DazFahy** [comment]
I finish work for Christmas on the 11th December, so will take a look at this the following week when I can hook up my test rig.
