### ISSUE TITLE
[Proposal] Support OpenDrain and OpenCollector options for GPIO PinMode

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#135]
GPIO `PinMode` currently only supports Input, Output, InputPullDown and InputPullUp.  There are other scenarios where outputs are open-drain and open-collector types and the API should accommodate.

## Rationale and Usage

I/O expanders are a good example where they have different types of I/O within a particular family and are differentiated by part numbers for the family.  In many cases, a user's hardware will be configured with the basic Input or Output `PinMode` values along with attaching external resistors for pull-up/down functionality.  However,  you can utilize internal circuitry in binding devices to perform this.  For example, the MCP23X09/MCP23X18 devices have open-drain outputs.  Therefore, you could update the GPIO Pull-up Resistor Configuration Register (GPPU) when opening pins when using as a controller.

## Example

You could have something similar below based on the [IGpioControllerProvider proposal](https://github.com/dotnet/iot/issues/125).

```csharp
var connectionSettings = new SpiConnectionSettings(0, 0);
var spiDevice = new UnixSpiDevice(connectionSettings);
var mcp23Sxx = new Mcp23Sxx(0, spiDevice);
GpioController mcp23SxxController = mcp23Sxx.GetDefaultGpioController();

// Now when you call the GpioController methods, the master controller will send
// the respective SPI commands to the binding behind the scenes to update its I/O.
//
// The code below would interact with the MCP23XXX related registers (IODIR, GPIO, GPPU, etc.)
// to configure the pin as an output and write the value.
mcp23SxxController.SetPinMode(1, PinMode.OpenDrainPullUp);
mcp23SxxController.Write(1, PinValue.High);
```

## Proposed Change

Update the GPIO `PinMode` to include the new values.  Summaries were left out for simplicity.
```csharp
public enum PinMode
{
    Input,
    Output,
    InputPullDown,
    InputPullUp,
    // The following are the proposed additions.
    OutputOpenDrain,
    OutputOpenDrainPullUp,
    OutputOpenCollector,
    OutputOpenCollectorPullDown
}
```
I have not checked throughout API, but will also need to update logic that checks if PinMode is of specific type.  For example, the GpioController.Write methods verify the mode is equal to Output before writing.

```csharp
// From GpioController.cs file.
if (_driver.GetPinMode(pinNumber) != PinMode.Output)
{
  throw new InvalidOperationException("Can not write to a pin that is not set to Output mode.");
}
```

## Open Questions

1. [Windows.Devices.Gpio.GpioPinDriveMode](https://docs.microsoft.com/en-us/uwp/api/windows.devices.gpio.gpiopindrivemode) is similar to `System.Device.Gpio.PinMode`.  It already includes current `PinMode` values and the values being proposed.  However, the names are slightly different for the open-collector types.  The question is should we stay consistent to Windows.Devices.Gpio (OutputOpenSource and OutputOpenSourcePullDown) or use OutputOpenCollector and OutputOpenCollectorPullDown?  I've mainly seen references to open-collector and not open-source while researching related content.  I'm not sure what the best approach would be in this case and would be content either way.  Open-source mentioned here during [this Libgpiod session](https://youtu.be/cdTLewJCL1Y?list=PLbzoR-pLrL6pISWAq-1cXP4_UZAyRtesk&t=14m).

## References
https://blog.digilentinc.com/open-collector-vs-open-drain/
**Section 1.5**: http://ww1.microchip.com/downloads/en/DeviceDoc/20002121C.pdf
https://docs.microsoft.com/en-us/uwp/api/windows.devices.gpio.gpiopindrivemode

**Comment by krwq** [comment]
[Triage] @pgrawehr has proposed ExtendedPinMode in https://github.com/dotnet/iot/pull/1397 which could as well solve this issue. Would that work here?
