### ISSUE TITLE
This driver is generic so it can not perform conversions between pin numbering schemes.

### ISSUE THREAD

**Issue by netleike** [dotnet/iot#1363]
I have updated the latest System.device.Gpio library
This driver is generic so it can not perform conversions between pin numbering schemes.
GpioController controller = new GpioController(System.Device.Gpio.PinNumberingScheme.Board);
If (!controller.IsPinOpen(pin))
{
Controller. OpenPin (pin);
Controller. SetPinMode (pin, System. The Device. The Gpio. PinMode. Output);
}
              
Controller. The Write (pin, System. The Device. The Gpio. PinValue. High);
Thread.sleep (1000);
Controller. The Write (pin, System. The Device. The Gpio. PinValue. Low);
Thread.sleep (1000);
Return the Content (" ok ");

**Comment by pgrawehr** [comment]
What hardware are you running on? 

Except for the Raspberry Pi, you cannot use PinNumberingScheme.Board. Use PinNumberingScheme.Logical instead.

**Comment by netleike** [comment]
Thank you the problem has been solved
