### ISSUE TITLE
Stylecop SA1008 creating issues with VS2019 autoformatting

### ISSUE THREAD

**Issue by Ellerbach** [dotnet/iot#1391]
**Describe the bug**

See the simple code below. Do `ctrl + k + d` for autoformatting in VS2019. and Stylecop is not happy because of rule SA1008

![image](https://user-images.githubusercontent.com/8145578/102981740-b2b28c00-4509-11eb-8cc2-c23777a19dec.png)

**Steps to reproduce**

```csharp
var platformChoice = Console.ReadKey();
Console.WriteLine();

if (platformChoice is not object or { KeyChar: not ('1' or '2') })
{
    Console.WriteLine("You have to choose a valid platform");
    return;
}
```

**Expected behavior**

Autoformatting should respect the rules or rules needs to be adjusted.

**Actual behavior**

Create an error which needs to be manually adjusted every time.

**Versions used**

Microsoft Visual Studio Enterprise 2019
Version 16.8.3

**Comment by pgrawehr** [comment]
Not sure, but it is possible that the settings in `.editorconfig` contradict the StyleCop rules in some points.

**Comment by Ellerbach** [comment]
[Triage] There are still few edge cases where there are conflits. We'll let this one open to make sure we don't forget to fix all those edge cases.

**Comment by Ellerbach** [comment]
[Triage]This seems to be fixed for now.
