### ISSUE TITLE
Where is the API docs?

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/iot#1399]

**Comment by Ellerbach** [comment]
@GF-Huang can you be a bit more precise please? What are you looking for exactly?
We do have documentation for every binding with a sample. Check any of the /src/devices
For System.Device.Gpio we do have as well in the documentation for example for SPI: https://github.com/dotnet/iot/blob/master/Documentation/raspi-spi.md

**Comment by krwq** [comment]
Do you mean https://docs.microsoft.com/en-us/dotnet/api/?view=iot-dotnet-1.1 ?

**Comment by GF-Huang** [comment]
yes，thanks

Krzysztof Wicher <notifications@github.com>于2021年1月3日 周日18:14写道：

**Comment by pgrawehr** [comment]
@krwq: He cool, didn't know that this was "officially" published. We should make sure we link there from the main Readme and also make sure the documentation is updated regularly.

**Comment by krwq** [comment]
Yes, https://github.com/dotnet/iot-api-docs is the repo. I'll need to ask people who created it to update it since it's currently only documenting version 1.1 (hopefully set auto-update on the repo).

**Comment by Ellerbach** [comment]
And we could as well add properly all the README.md and all the rest of the documentation. I've been using quit a lot DocFX and also wrote a TOC generator so I may have a look at this more deeply!

**Comment by Ellerbach** [comment]
[Triage] The question is answered. The process to update it is on its way. Feel free to reopen it if you have specific elements or you don't see anything updated in the next few weeks.
