### ISSUE TITLE
bouncetime

### ISSUE THREAD

**Issue by vulild** [dotnet/iot#1418]
请问有没有类似Python里的GPIO.add_event_detect(channel, GPIO.RISING, callback=my_callback, bouncetime=200)
bouncetime的防抖的功能

**Comment by krwq** [comment]
Hello @vulild, we only have GpioController but we do not have anything resembling bounce time. You can do something similar I have suggested in here: https://github.com/dotnet/iot/issues/674

**Comment by Ellerbach** [comment]
[Triage] As mentioned, this is a duplicate from #674, so I'm closing this issue. Please feel free to reopen if anything special.
