### ISSUE TITLE
Default branch has been renamed to main.

### ISSUE THREAD

**Issue by joperezr** [dotnet/iot#1421]
On Thursday, 28 January 2021 we're going to rename the default branch in this repository to main. For more details, see [our earlier announcement](https://github.com/dotnet/announcements/issues/172). Expect the process to begin after 5PM Pacific.

**NOTE: This process is now complete, rename has happened. Let us know if you hit any issues with changing your local fork or have any questions.**

**Comment by joperezr** [comment]
FYI: @pgrawehr @richlander @krwq @Ellerbach

**Comment by krwq** [comment]
I'd suggest to close this issue and unpin it soon. It's been couple of months since this has been announced
