### ISSUE TITLE
CharacterLcd sample does not compile

### ISSUE THREAD

**Issue by Apollo3zehn** [dotnet/iot#1437]
See: https://github.com/dotnet/iot/blob/main/src/devices/CharacterLcd/README.md

The second code samples contains the following line:
`using (var lcd = LcdRgb(new System.Drawing.Size...`

Instead it should be `using (var lcd = new LcdRgb(new System.Drawing.Size` ("**new**" is missing).

**Comment by Ellerbach** [comment]
Correct. Will be fixed in #1392.
If you copy/paste from the sample, it will work.

**Comment by Ellerbach** [comment]
[Triage] Closing as #1392 has fixed it.
