### ISSUE TITLE
Apply comments  from PR #133 related/can be found in SysFs driver implementation

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/iot#146]
1. Refactor Sysfs event handling logic, make all tests pass. 
2. Some comments for LibGpiod driver implementation PR https://github.com/dotnet/iot/pull/133 related to SysFs driver too. Apply those comments to SysFs driver and test accordingly such as:

https://github.com/dotnet/iot/pull/133#discussion_r244890760
https://github.com/dotnet/iot/pull/133#discussion_r244891801
https://github.com/dotnet/iot/pull/133#discussion_r245413628
https://github.com/dotnet/iot/pull/133#discussion_r245459454

**Comment by joperezr** [comment]
@buyaa-n is this not done yet?

**Comment by buyaa-n** [comment]
Not yet :( ...

**Comment by buyaa-n** [comment]
Some of the comments doesn't apply to Sysfs driver anymore and the event handling section for sysfs driver need more refactoring, so am gonna update this issue for refactoring the driver

**Comment by joshfree** [comment]
marking this as up-for-grabs in case someone from the community wants to fix this before developers here can get to this issue
