### ISSUE TITLE
VideoDevice error

### ISSUE THREAD

**Issue by MaxPrimeAERY** [dotnet/iot#1461]
**Describe the bug**

VideoDevice doesn't work for me properly.  I get an error in this part of code
video = device.CaptureContinuous(); // I get System.IO.MemoryStream
Bitmap myBitmap = new Bitmap(video);

System.ArgumentException: Parameter is not valid.
at System.Drawing.Image.InitializeFromStream(Stream stream)
at System.Drawing.Bitmap..ctor(Stream stream)

**Comment by Ellerbach** [comment]
[Triage] @MaxPrimeAERY can you please check if #1474 is fixing your issue. The new release 1.4 is containing this PR already. So please give it a try and let us know if you still have this issue.
