### ISSUE TITLE
Update NuGet feed

### ISSUE THREAD

**Issue by richlander** [dotnet/iot#1492]
We need the following packages added to our feed ([whichever one is the right one](https://github.com/dotnet/iot/blob/main/NuGet.config)).

- StyleCopy.Analyzers 1.2.0-beta.333
- Moq 4.16.1
- Microsoft.Net.Compilers.Toolset 3.9.0
- Microsoft.CodeAnalysis.CSharp.Scripting 3.9.0

Can the Microsoft.* packages be added to some auto-push list? It seems off to have to request those.

**Comment by joperezr** [comment]
Micrsoft.* packages were already in the internal feed. The PR that was auto updating those packages were failing due to different reasons. We have now pushed StyleCop and Moq packages to the internal feed so I'll go ahead and close this issue.
