### ISSUE TITLE
Linux-arm LIBGPIOD: PinValueChangedEvent  consumes too much CPU

### ISSUE THREAD

**Issue by Alex-111** [dotnet/iot#1539]
**Describe the bug**

When registering a callback for pin events, then the CPU goes up to about 12% CPU usage just for a single pin:

**Steps to reproduce**

```csharp
 class Program
    {
        static void Main(string[] args)
        {
            var gpioController = new GpioController(PinNumberingScheme.Logical, new LibGpiodDriver(4));

            gpioController.OpenPin(9, PinMode.Input);
            gpioController.RegisterCallbackForPinValueChangedEvent(9, PinEventTypes.Falling | PinEventTypes.Rising, (sender, e) =>
            {
                Console.WriteLine("Pin Event: " + e.PinNumber.ToString() + " - " + e.ChangeType.ToString());
                if (e.ChangeType == PinEventTypes.Rising || e.ChangeType == PinEventTypes.Falling)
                {

                   
                }
            });


            Console.ReadLine();
        }
    }
```

**Expected behavior**

CPU should stay near 0%

**Actual behavior**

With my sample code above CPU is about 12% on a linux-arm embedded board. It gets worser if there are eventhandler on more than one pin...

**Versions used**

.NET 5.0.5 self-contained
 
Version of System.Device.Gpio package 1.4

The CPU usage decreases to about 0-1 %  if I use a longer wait delay here -> instead of 1_000_000 I tried 50_000_000:
![image](https://user-images.githubusercontent.com/18511703/118497972-d62edb00-b725-11eb-82a6-e33cab1393d8.png)

if increasing the wait time has no drawbacks, then it would be better to increase it by default or at least at a parameter for this.

**Comment by krwq** [comment]
@Alex-111 closing this since the PR is merged, please re-open if you feel there is anything left
