### ISSUE TITLE
Asus Tinker

### ISSUE THREAD

**Issue by mrccarvalho** [dotnet/iot#1575]
**Cannot Write to  Asus Tinker GPIOs / Can we Use this Library With Asus Tinker ?**

 tried to use the Blink Led sample to start working with asus tinker GPIOs.
The Led is always ON and do not Blink.
The console app it is fine and gives no error.

Thanks,
Best Regards,
Roger

**Comment by ZhangGaoxing** [comment]
You can try this and refer to the datasheet for pin mapping
https://github.com/dotnet/iot/tree/main/src/devices/Gpio/Drivers/Rockchip

**Comment by mrccarvalho** [comment]
> 
> 
> You can try this and refer to the datasheet for pin mapping
> https://github.com/dotnet/iot/tree/main/src/devices/Gpio/Drivers/Rockchip

Thanks ZhangGaoxing, 
I will investigate about this and make a test with it.

**Comment by mrccarvalho** [comment]
After doing some tests, i find that it is possible to read and write to asus tinker's gpio pins. 

I use the 163 pin number that corresponds to the physical pin number 18  on the tinker board.
Can confirm that the next code wotks fine.

`using System;
using System.Device.Gpio;
using System.Threading;

Console.WriteLine("Blinking LED. Press Ctrl+C to end.");
int pin = 163;   // 163 corresponds to the physical pin number 18  on tinker board
using var controller = new GpioController();
controller.OpenPin(pin, PinMode.Output);
bool ledOn = true;
while (true)
{
    controller.Write(pin, ((ledOn) ? PinValue.High : PinValue.Low));
    Thread.Sleep(1000);
    ledOn = !ledOn;
}`

Thanks!
Best Regards!

**Comment by Ellerbach** [comment]
Great news! So closing this issue.
