### ISSUE TITLE
Add support c MPU-6050 Gyroscope

### ISSUE THREAD

**Issue by mcdis** [dotnet/iot#1645]
Please add support for MPU-6050 gyroscope series

**Comment by Ellerbach** [comment]
[Triage] That's a nice sensor to grab and implement. It seems like this sensor is quite old at the same time. The MPU6500 version may be compatible with this one for the registers and would make it fairly easy to implement.

**Comment by krwq** [comment]
[Triage] We don't keep issues with device implementation request. If anyone is interested in contributing please open a PR. If needs discussion please re-open
