### ISSUE TITLE
Add to PN532 abbility to ignore firmware version ack by i2c interface

### ISSUE THREAD

**Issue by mcdis** [dotnet/iot#1646]
Some cheap copies, which are based on PN 521, do not respond to the request for the firmware version, but they ask to send it before working.
In arduino, in the source, they just ignore the answer.

Googling for 5 minutes, and you will find a decent amount of queries that people can't read the get firmware version answer.

It worked for me when, instead of exception, I set to ignore the answer.
This only applies to the i2c interface.

**Comment by joperezr** [comment]
Closed by #1651
