### ISSUE TITLE
Add bindings for Polar RE07S (Wireless Heart Rate Receiver)

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#168]

**Comment by joshfree** [comment]
@buyaa-n could you help pick this one up?

**Comment by safern** [comment]
@buyaa-n I have some progress on how to gather data from this guy, just didn't have the time to finish the binding, it should be fairly simple though.

**Comment by krwq** [comment]
[Triage] It's nice to have issue but considering more than 3 years have passed since this was created and no one requested it closing the issue. We're welcome to take any contributions but we don't need an issue lying around
