### ISSUE TITLE
Add all ADC drivers to IoT.Device.ADC namespace

### ISSUE THREAD

**Issue by fkromer** [dotnet/iot#1691]
**Is your feature request related to a problem? Please describe.**

From the API it's not obvious immediatelly which ADC chips are supported. If one looks only into [IoT.Device.Adc namespace](https://docs.microsoft.com/en-us/dotnet/api/iot.device.adc?view=iot-dotnet-1.5) it seems like only a few chips are supported. However if one takes a closer look into the overall [IoT.Device namespace](https://docs.microsoft.com/en-us/dotnet/api/?view=iot-dotnet-1.5&term=IoT.Device) one figures out that there are supported quite some other chips as well. ADC chip drivers not yet int the namespance I've found so far:

- [IoT.Device.Ads1115](https://docs.microsoft.com/en-us/dotnet/api/iot.device.ads1115?view=iot-dotnet-1.5)
- [Iot.Device.Mcp3428](https://docs.microsoft.com/en-us/dotnet/api/iot.device.mcp3428?view=iot-dotnet-1.5) (Mcp3426, Mcp3427, Mcp3428, Mcp3426, Mcp3427, Mcp3428)
- [IoT.Device.Tlc1543](https://docs.microsoft.com/en-us/dotnet/api/iot.device.tlc1543?view=iot-dotnet-1.5)

**Describe the ideal solution**

It would be helpful if all ADC drivers would [add themself to the corresponding namespace like these do](https://github.com/dotnet/iot/search?p=1&q=IoT.Device.Adc).

**Comment by fkromer** [comment]
@Ellerbach Relates to https://github.com/dotnet/iot/issues/1692 and https://github.com/dotnet/iot/issues/1693 .

**Comment by fkromer** [comment]
> ... device that are ADC from https://github.com/dotnet/iot/tree/main/src/devices#analogdigital-converters being all in the same namesapce, correct?

As documentation which is not autogenerated tends to be outdated most devs prefer to explore the API in their IDE of choice. Namespaces are a great way for "IDE-base autocompletion kind of" API guidance. As soon as I know the API of the drivers better I'm happy to contribute.

**Comment by krwq** [comment]
Thanks @fkromer. I'll close this issue because we've already had some discussion on this subject in the past and we concluded it's better to keep the doc in sync than trying to represent tags as a namespace.
