### ISSUE TITLE
SensorHub: Improper handling of STATUS_REG

### ISSUE THREAD

**Issue by wdolek** [dotnet/iot#1694]
**Describe the bug**

There's external temperature sensor and light sensor on [Sensor Hub](https://wiki.52pi.com/index.php/DockerPi_Sensor_Hub_Development_Board_SKU:_EP-0106) which status can be read from single registry (`STATUS_REG (0x04)`).

For some reason when board is placed in complete darkness, light sensor reports failure (value `status = 0x08`) - causing check for no error to fail when reading external temperature.

At same time (in complete darkness) it is possible to read external sensor temperature directly from i2c.

**Steps to reproduce**

```csharp
// turn off lights (causing light sensor to fail)
if (sh.TryReadOffBoardTemperature(out var t))
{
    Console.WriteLine($"OffBoard temperature {t}");
}
else
{
    Console.WriteLine("You can measure external temperature only with lights on!");
}
```

**Expected behavior**
Output:
```
OffBoard temperature 23 °C
```

**Actual behavior**
Output:
```
You can measure external temperature only with lights on!
```

In complete darkness, light sensor reports fail trough `STATUS_REG (0x04)`, value `0x08` which causes `TryReadOffBoardTemperature` to not read value from external sensor:
```
            if (status.Equals((byte)RegisterStatusErrors.NO_ERROR))
            {
                temperature = Temperature.FromDegreesCelsius(ReadRegister(Register.TEMP_REG));
                return true;
            }

            return false; // <-- returns here
```

**Versions used**

- using .net 5.0 self-contained build `dotnet publish -c Release -r linux-arm64 -o app/`
- `Iot.Device.Bindings` `1.5.0`
- `System.Device.Gpio` `1.5.0` (transient dependency)

**Comment by joperezr** [comment]
Thanks for finding the issue and for submitting a PR to fix it. We will review it shortly.
