### ISSUE TITLE
Add bindings for Stepper motor (i.e. 17HS13-0404S)

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#173]
This will need to be investigated if we will have a generic StepperMotor device or both generic and more specific version with tiny bit more info

**Comment by johnastaf** [comment]
I'm working on binding for 28byj-48 motor from Grove kit. I will send PR soon

**Comment by joshfree** [comment]
Thanks @johnastaf for picking this one up 😃

**Comment by krwq** [comment]
We currently have Uln2003 (https://github.com/dotnet/iot/tree/master/src/devices/Uln2003) so I'd consider this issue done. There are probably more stepper motor drivers but we can reiterate on that implementation from there whenever we find that we need to add support for more
