### ISSUE TITLE
Add bindings for RFID-RC522 (MF-RC522)

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#175]
This is currently WIP https://github.com/dotnet/iot/pull/293 - please pick up from here when implementing (PR is closed)

**Comment by robertsundstrom** [comment]
@krwq I just started to port a module that I had previously contributed to another project, then I saw that you already had started making one. What is the status?

Anyway, here is my port: https://github.com/robertsundstrom/iot/commit/7cfba1f35dd5f5d5eb0b16347c4453eb2fab229d

It needs some polishing on the interface, as it is based on older code written in Java and Python.

**Comment by krwq** [comment]
@robertsundstrom I have only barebones (the super low level stuff), reading UIDs from MIFARE tags and detecting presence of card (no authentication) but was mostly porting https://github.com/miguelbalboa/rfid with some improvement and the code is currently very far from pretty (although I have made it mostly non-allocating) - I still do not fully understand some of the pieces from that code (I only started working on this again today after not touching the code for 2 weeks). You can find the code in here (I usually push to the private fork first though but can push directly to public) - I didn't even call my project correctly at first (RfidRc522 instead of MFRC522): https://github.com/krwq/iot/tree/rfid_rc522/src/devices/RfidRc522

Your code seems much simpler than mine so what we can do is perhaps:
- figure out what APIs do we want
- combine both pieces of code together (assuming there is anything useful in mine which you don't have)

what I don't like in my version of code is that there is a lot of magic numbers all around and basically impossible to read without the spec (although yours is simpler and much easier to read still has many "magic" pieces).

I currently lack of higher level context on how exactly RFID tags are used. I could only think of reading tag IDs and I know that at least some tags support some form of authentication but have very little knowledge about how this exactly works... MFRC522 has fairly hard to read datasheet (at least for me) although have found some more interesting collection of datasheets in here: https://github.com/dalmirdasilva/ArduinoRadioFrequencyIdentification/tree/master/MifareClassic/datasheet but haven't had time to skim through that yet

**Comment by krwq** [comment]
Seems https://github.com/dalmirdasilva/ArduinoRadioFrequencyIdentification/blob/master/ReaderMFRC522/datasheet/TagTypes.pdf has some more high level description on different types of tags. All tags have some kind of UID and some devices allow to change the data and then permanently lock the data. Depending on the tag type they have different protocols on what can be done on them with some common stuff.

My rough idea (feel free to propose something better since I only have some basic knowledge in the subject) - I'd split this into 2 parts:
- purely MF-RC522 - basically provides anything to communicate with PICC/tag - so something like both of us wrote with some parts (at least in my case) removed and with some better APIs (I think your design might be closer to this), so basically stuff like: TurnOn/OffAntenna, SendRecieveToPicc etc.
- for each tag type write a class which communicates with it and exposes its interface (so class takes MF-RC522 class as an input or reverse MF-RC522 takes list of supported protocols) - if there is some common denominator we can add it directly to to MF-RC522 or have a base class like i.e. RfidTag

First version should support at minimum 1 or 2 most common tag types. I currently got this set: https://www.banggood.com/RC522-Chip-IC-Card-Induction-Module-RFID-Reader-p-81067.html?p=DQ30066511122014069J&utm_campaign=educ8stv&utm_content=3216&cur_warehouse=CN

**Comment by krwq** [comment]
@robertsundstrom also please make sure the license on the code you are porting is fine (in the case of library I shared it is public domain)

**Comment by robertsundstrom** [comment]
@krwq I also lack sufficient knowledge about the hardware and protocol.

As I have said, the code was ported to C#, and then rewritten when I contributed it to Unosquare.RaspberryIO. They built a thin but better interface.

I suggest having a look at it.

**Comment by robertsundstrom** [comment]
Unosquare.RapsberryIO

Source: https://github.com/unosquare/raspberryio/tree/master/src/Unosquare.RaspberryIO.Peripherals/Rfid

Playground: https://github.com/unosquare/raspberryio/blob/master/src/Unosquare.RaspberryIO.Playground/Program.Rfid.cs

**Comment by robertsundstrom** [comment]
I would not create a higher level abstraction unless the purpose is to handle multiple types of readers and formats through one common interface.

**Comment by krwq** [comment]
fair enough, @robertsundstrom I'm fine with you picking this up and I can help/join in both writing and testing. Please make sure to add some APIs to read UID and add couple of samples on the authentication. Feel free to use the code I shared in any way if you find anything useful there. The moment we add second similar device we can think about having common abstraction - until then I'd stick to being device specific

**Comment by robertsundstrom** [comment]
Alright. I will see what I can accomplish. Will notify when I have something.

**Comment by robertsundstrom** [comment]
After some experimentation: I have updated the commit to the branch in my fork: https://github.com/robertsundstrom/iot/commit/293e87e45323f36c10109c332fbfe3740ebcaa91

Tags are being read correctly now.

I originally ported the code from Python and I did some mistakes that they (Unosquare) discovered. That is now fixed here as well.

The interface is the original and it should reflect the terminology used in the actual protocol. 

Some refactoring, changes of variable names and such are welcome.

Functionality other than reading card needs to be tested as well.

**Comment by krwq** [comment]
I've added comments on that commit - I think as long as we don't deviate much from original naming it should be fine to deviate. (i.e. AntiColl => AntiCollision)

I'd recommend creating PR with this. Also please make sure to add samples for the common scenario which end up writing tag (currently I've seen a sample but for someone who doesn't have any knowledge on the subject it might be hard to understand)

**Comment by robertsundstrom** [comment]
> I've added comments on that commit - I think as long as we don't deviate much from original naming it should be fine to deviate. (i.e. AntiColl => AntiCollision)
> 
> I'd recommend creating PR with this. Also please make sure to add samples for the common scenario which end up reading tag (currently I've seen a sample but for someone who doesn't have any knowledge on the subject it might be hard to understand)
> 
> (i.e create one section in the readme per scenario)

Agree.

I'm on it! Will go through your comments when I've done my own refactoring.

I will submit a PR when I'm ready.

**Comment by krwq** [comment]
Ref: https://github.com/dotnet/iot/issues/320

**Comment by robertsundstrom** [comment]
I have now got a proper workstation at home. This enables me to resume my work on this binding. My goal is to clean it up. 

I will reopen the PR and fix what has been pointed out.

**Comment by krwq** [comment]
@robertsundstrom please wait for @Ellerbach to comment since he was planning to merge our work with his PN532 (#320) which he already got much further than we did (per our offline conversation). We want to merge as much code as possible here since this code is rather complicated comparing to other bindings.

**Comment by robertsundstrom** [comment]
@krwq OK. Anyway, I have updated my user branch.

**Comment by Ellerbach** [comment]
@robertsundstrom, I have been working on it a bit. As @krwq mentionned, I have been working on the PN532 and I'm about to propose a first PR. I took out what is related to the Mifare cards and created an abstract function that can be impleted by any RFID/NFC reader that supports 14443 for thos kind of cards. I did the same for credit cards (144443 type B) for a project. And The same function can be used by any reader as well.
@robertsundstrom , where can I find your branch?

**Comment by robertsundstrom** [comment]
@Ellerbach Here, https://github.com/robertsundstrom/iot/tree/Mfrc522 🙂

**Comment by Ellerbach** [comment]
@robertborr , I tryed my reader on an ESP8266 and looks like it has some issues. As soon as I do an authentication, it blocks. Same behavior I had with .NET Core. I did couple of modifications in your files and Added few registers to make it easier to debug.
Please have a look at: https://github.com/Ellerbach/Pn532/tree/master/Mfrc522
I have implemented as well a full Mifare card (it's currently Under PR) but you have the full project available. And you can try what I did. It may work (again, I had issues with the hardware).

**Comment by robertsundstrom** [comment]
I should have mentioned that I don’t have focused on authentication. It was the last things I worked on before pausing. So it os not working at the moment. I’ll have a look at it later.

If you want, you could have a look at Unosquare’s code (link either here in issue or in the PR). It is based on my original code. They might have fixed the issue there.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by robertborr** [comment]
@Ellerbach - while this is indeed interesting, I'm probably not the person you want. :)

**Comment by robertsundstrom** [comment]
I left a comment here: https://github.com/Ellerbach/Pn532/issues/1

**Comment by robertsundstrom** [comment]
What is the status?

**Comment by krwq** [comment]
@robertsundstrom [PN532 is merged](https://github.com/dotnet/iot/tree/master/src/devices/Pn532), for MFRC522 not sure cc: @Ellerbach

**Comment by robertsundstrom** [comment]
@krwq It is not inte package @Ellerbach

**Comment by forki** [comment]
Is there something I could test for MFRC522?

**Comment by forki** [comment]
@robertsundstrom did you create a PR? where is it?

**Comment by Ellerbach** [comment]
I4ve been working on the MFRC522 but it does not even work correctly with an Arduino. Authentication for the Miface cards is not working correctly. Even with various Arduino library, I did not managed to make it working well enough. I had the same issues with .NET Core IoT. so I basically drop the work to focus more on the PN532 which is indeded a great chip. 
If anyone managed to find a way to make the authentication working perfectly, don't forget to implement the CardTransciver class: https://github.com/dotnet/iot/blob/master/src/devices/Card/CardTransceiver.cs
This will allow to reuse all the Miface card code. 
In general, any RFID reader we'll write has to implement this class to support all the common card work already published.

**Comment by forki** [comment]
What's the status of MFRC522?

**Comment by Ellerbach** [comment]
> What's the status of MFRC522?

I did spend quite some time and decided to stop as I didn't even manage to make it working correctly on an Arduino with the official libraries and the basic examples. Authentication failed on all my cards even specifying correct keys. I bought 2 different hardware and I have the same issue on both hardware, so very unlikely that both are defective. This hardware is very limited anyway.
That said, if you have time, you can try to make it working. Again, to get the support of all the libraries that are already in the framework, implement CardTrasceiver and all the rest will be magic.

**Comment by forki** [comment]
Is there any progress on this?

**Comment by Ellerbach** [comment]
Not really, there seems to be an issue with the hardware itself. It's working ok on an Arduino for example but not with an ESP8266. I have multiple versions of the MFRC522 so tried with different hardware. Result is never the same. So I would prefer not to spend too much time on it giving the fact that there are more readers, on the same price range with better features reading a broader range of cards which are already implemented.

**Comment by forki** [comment]
>  issue with the hardware itself

It works in many many IoT scenarios with node. I really was hoping to eventually port it to dotnet core especially since asp.net core deprecated INodeServices. Bummer

**Comment by krwq** [comment]
@Ellerbach this is also closed with your recent PR

**Comment by forki** [comment]
@krwq are there docs on how to use this?

**Comment by krwq** [comment]
Hey @forki,

Refer to README.md and samples folder here:
https://github.com/dotnet/iot/tree/master/src/devices/Mfrc522

If you haven't bought your reader then consider buying this one instead:
https://github.com/dotnet/iot/tree/master/src/devices/Pn532
