### ISSUE TITLE
Add bindings for HT16K33

### ISSUE THREAD

**Issue by joperezr** [dotnet/iot#179]
This is a 16*8 LED Controller display with keyscan and supports I2c.

**Comment by joperezr** [comment]
Here is an interesting link with a similar implementation for Python: https://github.com/adafruit/Adafruit_Python_LED_Backpack/blob/master/Adafruit_LED_Backpack/SevenSegment.py

**Comment by tawalke** [comment]
Will work on this one.

**Comment by krwq** [comment]
Hey @tawalke, is the branch ready for review yet? What's the remaining work there? :smile:

**Comment by tawalke** [comment]
Hi Krzysztof:

The base class lib is completed, I need to publish the changes made to the 7Segment class for this lib so that the branch can be reviewed.  Will do later this week.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by gLes** [comment]
Hi!

As I see this development seems to be stuck in limbo.

I have a working implementation for this controller and with a little cleanup I can put it into a PR in a day or two if you're interested.

**Comment by krwq** [comment]
@gLes thanks! Please do, also please check @tawalke's implementation and see if there is anything there you can add to your implementation:
https://github.com/dotnet/iot/tree/015f68cdd5b01a3eeb8ee2043382e0723241f246/src/devices/HT16K33

**Comment by gLes** [comment]
Can you give me some preliminary insight on my commit? I tried to follow suite, but it would be nice if someone could confirm I'm on the right path here 🙂

Usage, samples, tests, etc. are coming soon...

**Comment by krwq** [comment]
@gLes I haven't reviewed the whole thing, just quickly skimmed and added couple of comments. I think from API perspective you should look at similar device: https://github.com/dotnet/iot/tree/master/src/devices/Tm1637 and see how it was made as an example and do it as similar as possible (if you find that you copy paste a code consider joining some pieces of the code if possible)

**Comment by krwq** [comment]
This is already done: https://github.com/dotnet/iot/blob/master/src/devices/Display/README.md
