### ISSUE TITLE
Documentation for V2.0 is missing

### ISSUE THREAD

**Issue by pgrawehr** [dotnet/iot#1805]
The official documentation at https://docs.microsoft.com/de-de/dotnet/api/?view=iot-dotnet-1.1 has not yet been updated to 2.0. 
Also, some of the examples and recommendations on https://docs.microsoft.com/de-de/dotnet/iot/ are out of date.

**Comment by joperezr** [comment]
cc: @CamSoper Do you know how can we make sure 2.0 docs show up in docs.microsoft.com?

**Comment by CamSoper** [comment]
@joperezr Yes! We need to do the same process we did for the 1.1 APIs... but I don't remember what that process is. @gewarren, little help please? 🙏🏻

**Comment by gewarren** [comment]
@CamSoper You can submit a request here: https://aka.ms/publish-on-docs/reference

**Comment by CamSoper** [comment]
@joperezr Since you own the code I think it probably makes more sense for you to put that request in, but I'm happy to do it if you need me to.

**Comment by krwq** [comment]
I've requested for 2.0 and 2.1 docs to be generated and this is now fixed, closing the issue
