### ISSUE TITLE
Consuming the library from a .NET5.0 project fails with "Failed to create CoreCLR, HRESULT: 0x80070057"

### ISSUE THREAD

**Issue by pgrawehr** [dotnet/iot#1807]
**Describe the bug**

When using Iot.Device.Bindings.dll from a project targetting .NET 5.0, the program fails to start and "Failed to create CoreCLR, HRESULT: 0x80070057" is printed. Nothing more happens. If the library is lazy-loaded late in your application, a "FileNotFoundException" is thrown about a file that is clearly there. 

**Steps to reproduce**

```text
C:\projects\iot\>build
....
cd src\devices\HardwareMonitor\samples\bin\Debug\net6.0
C:\projects\iot\src\devices\HardwareMonitor\samples\bin\Debug\net6.0>OpenHardwareMonitor.Samples.exe
... (some error about communication failure)
```
then, in HardwareMonitor.csproj change TFM to "net5.0"
```text
C:\projects\iot\>build
....
cd src\devices\HardwareMonitor\samples\bin\Debug\net5.0
C:\projects\iot\src\devices\HardwareMonitor\samples\bin\Debug\net5.0>OpenHardwareMonitor.Samples.exe
Failed to create CoreCLR, HRESULT: 0x80070057
```

**Expected behavior**

The program works

**Actual behavior**

The above-mentioned error is printed

**Versions used**

Built from `main` branch, installed all relevant .NET SDK versions.

**Comment by krwq** [comment]
[Triage] Per @pgrawehr we can close it
