### ISSUE TITLE
Add bindings for BH1750 (Light Sensor)

### ISSUE THREAD

**Issue by joperezr** [dotnet/iot#181]

**Comment by joperezr** [comment]
I'll go ahead and take this one.

**Comment by ZhangGaoxing** [comment]
I noticed that you closed #182. Can I help with this issue? I can submit a PR to complete BH1750 and add some new features. I can easily migrate the code I wrote before. @joperezr  😄 https://github.com/ZhangGaoxing/windows-iot-demo/blob/master/src/BH1750FVI/03_Source/BH1750FVIDemo/BH1750FVI.cs

**Comment by joperezr** [comment]
Hey @ZhangGaoxing, thanks for picking up the work. I will take a look at your PR :).
