### ISSUE TITLE
where should I add a Virtual GPIO device？

### ISSUE THREAD

**Issue by HumJ0218** [dotnet/iot#1812]
For testing I'm coding at a virtual GPIO device.

Should I add it as a GpioDriver in System.Device.Gpio or a device binding like SoftwareSpi in Iot.Devices.Binding?

**Comment by Ellerbach** [comment]
Hi @HumJ0218, I would say on the IoT.Devices. We try to keep only the real hardware drivers that are the most common in System.Devices. Thnaks!

**Comment by pgrawehr** [comment]
We already have a bunch of extra drivers in `src\devices\gpio\drivers`. And some special virtual drivers in `src\devices\board\` as well. I'd use one of these places.
