### ISSUE TITLE
Mfrc522 - MifareCardCommand.Write16Bytes not working, always return code -1

### ISSUE THREAD

**Issue by fwullschleger** [dotnet/iot#1862]
**Describe the bug**

I hooked up a [RFID Kit](https://www.funduinoshop.com/elektronische-module/wireless-iot/rfid-nfc/rfid-kit-mit-mifare-rc522-empfaenger) to a Raspberry Pi 3 Model B.

Working with the [sample](https://github.com/dotnet/iot/blob/main/src/devices/Mfrc522/samples/Program.cs) everything worked   as expected. Unfortunately I could not find a sample for writing to a card.

I wrote my own prototype for writing to a card using the same configurations as in the [sample](https://github.com/dotnet/iot/blob/main/src/devices/Mfrc522/samples/Program.cs) code.
I had no success writing to a card. I always got the ReturnCode -1.
Reading, Authentication, BlockAccess are working as expected as can be seen in the sample code below.

With the same hardware setup and the python code from this [blogpost](https://pimylifeup.com/raspberry-pi-rfid-rc522/) and the python library [mfrc522](https://github.com/pimylifeup/MFRC522-python/tree/master/mfrc522) I was able to write to the same card without any issues.

**Steps to reproduce**

```csharp
using System.Device.Spi;
using System.Text;
using Iot.Device.Board;
using Iot.Device.Card.Mifare;
using Iot.Device.Mfrc522;
using Iot.Device.Rfid;

Console.WriteLine("Hello, World!");

var board = Board.Create();
var gpioController = board.CreateGpioController();
SpiConnectionSettings connection = new SpiConnectionSettings(0, 0);
connection.ClockFrequency = 1_000_000;
SpiDevice spi = SpiDevice.Create(connection);
MfRc522 mfrc522 = new MfRc522(spi, 4, gpioController, false);

Console.WriteLine($"Version: {mfrc522.Version}, version should be 1 or 2. Some clones may appear with version 0");

bool res;
Data106kbpsTypeA card;
do
{
    res = mfrc522.ListenToCardIso14443TypeA(out card, TimeSpan.FromSeconds(2));
    Thread.Sleep(res ? 0 : 200);
} while (!res);

Console.WriteLine("Card detected!");

var mifare = new MifareCard(mfrc522!, 0);
mifare.SerialNumber = card.NfcId;
mifare.Capacity = MifareCardCapacity.Mifare1K;
mifare.KeyA = MifareCard.DefaultKeyA.ToArray();
mifare.KeyB = MifareCard.DefaultKeyB.ToArray();
int ret;

mifare.BlockNumber = 11;
mifare.Command = MifareCardCommand.AuthenticationB;
ret = mifare.RunMifareCardCommand();
logMifareCardToConsole(mifare, ret);

mifare.Command = MifareCardCommand.Read16Bytes;
ret = mifare.RunMifareCardCommand();
logMifareCardToConsole(mifare, ret);

mifare.BlockNumber = 8;
var accessType = mifare.BlockAccess(mifare.BlockNumber,mifare.Data);
Console.WriteLine($"Bloc: {mifare.BlockNumber}, Access: {accessType}");

mifare.Command = MifareCardCommand.Read16Bytes;
ret = mifare.RunMifareCardCommand();
logMifareCardToConsole(mifare, ret);

mifare.Command = MifareCardCommand.AuthenticationB;
ret = mifare.RunMifareCardCommand();
logMifareCardToConsole(mifare, ret);

mifare.Data = new byte[16]
    { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF };
mifare.Command = MifareCardCommand.Write16Bytes;
ret = mifare.RunMifareCardCommand();
logMifareCardToConsole(mifare, ret);

mifare.Command = MifareCardCommand.Read16Bytes;
ret = mifare.RunMifareCardCommand();
logMifareCardToConsole(mifare, ret);

void logMifareCardToConsole(MifareCard mifareCard, int i)
{
    Console.WriteLine(
        $"BlockNumber: {mifareCard.BlockNumber}, Command: {mifareCard.Command}, ReturnCode: {i}, Data: {BitConverter.ToString(mifareCard.Data)}");
}
```

**Console Output:**
```
Hello, World!
Version: 2.0, version should be 1 or 2. Some clones may appear with version 0
Card detected!
BlockNumber: 11, Command: AuthenticationB, ReturnCode: 0, Data: 
BlockNumber: 11, Command: Read16Bytes, ReturnCode: 16, Data: 00-00-00-00-00-00-FF-07-80-69-FF-FF-FF-FF-FF-FF
Bloc: 8, Access: ReadKeyA, ReadKeyB, WriteKeyA, WriteKeyB, IncrementKeyA, IncrementKeyB, DecrementTransferRestoreKeyA, DecrementTransferRestoreKeyB
BlockNumber: 8, Command: Read16Bytes, ReturnCode: 16, Data: 20-20-20-20-20-20-20-20-20-20-20-20-20-20-20-20
BlockNumber: 8, Command: AuthenticationB, ReturnCode: 0, Data: 20-20-20-20-20-20-20-20-20-20-20-20-20-20-20-20
BlockNumber: 8, Command: Write16Bytes, ReturnCode: -1, Data: FF-FF-FF-FF-FF-FF-FF-FF-FF-FF-FF-FF-FF-FF-FF-FF
```

**Expected behavior**

ReturnCode of Command Write16Bytes >= 0

**Actual behavior**

ReturnCode of Command Write16Bytes always -1

**Versions used**

- Version of `System.Device.Gpio` package: 2.1.0
- Version of `Iot.Device.Bindings` package (not needed if bug is in `System.Device.Gpio`): 2.1.0
- `dotnet --info` on the machine being used to build
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    02d5242ed7

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.102/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
- Raspberry Pi 3 Model B v1.2, latest versions installed, spi enabled
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
```

**Comment by Ellerbach** [comment]
Thanks for the details of the submission. Have you try to reauthenticate right before writing? I remember that this reader is a bit weird sometimes.

**Comment by fwullschleger** [comment]
> Thanks for the details of the submission. Have you try to reauthenticate right before writing? I remember that this reader is a bit weird sometimes.

Yes I have tried that. Sadly with no success. I updated my initial comment accordingly.
- I tried authenticating with both KeyA and KeyB right before writing (in separate tries/code).
- With KeyA I had no success with the authentication.
- With KeyB I got the same result stated in my initial comment.

Still with the python code the writing works flawlessly. So my guess would be that the Reader cannot be the problem. Anyways I should try another different reader.
@Ellerbach What exactly was weird with the reader? Maybe some insides help.

**Comment by Ellerbach** [comment]
Thanks for the additional data, so clearly a code problem!

> What exactly was weird with the reader? Maybe some insides help.

A lot of things compare to other readers :-) First is the chipselect that is really used as a trigger but as you can read, this is not the issue.

Then, if you look at this key function: https://github.com/dotnet/iot/blob/6be64b7477d86aca49503498e862d7be9962489d/src/devices/Mfrc522/Mfrc522.cs#L450
The authentication requires specific flags to be setup.

It has as well its own authentication function: https://github.com/dotnet/iot/blob/6be64b7477d86aca49503498e862d7be9962489d/src/devices/Mfrc522/Mfrc522.cs#L553

So between both and the rest of the code, something is maybe missing. Follow the code and you'll most likely spot out what can be missing.

I don't really have the rime now to look at this.

**Comment by fwullschleger** [comment]
Thank you for your clarifications.
I will order a different reader and try with that first.

**Comment by fwullschleger** [comment]
@Ellerbach Do you have a recommendation which RFID Reader and Chip I should try instead?

**Comment by Ellerbach** [comment]
> @Ellerbach Laurent Ellerbach FTE Do you have a recommendation which RFID Reader and Chip I should try instead?

* PN5180: https://github.com/dotnet/iot/tree/main/src/devices/Pn5180
* PN532: https://github.com/dotnet/iot/tree/main/src/devices/Pn532

Those are much much much better readers! Supporting as well a larger variety of cards

**Comment by fwullschleger** [comment]
Thank you very much! I will look into them.
