### ISSUE TITLE
Is there a way for mpu6050 to obtain the angle? Because I use Arduino, there are ready-made libraries

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/iot#1914]
Is there a way for mpu6050 to obtain the angle? Because I use Arduino, there are ready-made libraries

**Comment by Ellerbach** [comment]
@bbhxwl this is not an issue. Please check out trigonometry and how to calculate an angle. The formula in pseudo code is the following:

Heading angle (degrees) = 180 * atan2 (Y ,X) / PI

This is not related to any binding. This is more about helpers that you can build yourself. I recommend you to read about all those online. See for example: https://en.wikipedia.org/wiki/Heading_(navigation). There are others depending on what you need.
