### ISSUE TITLE
LibGpiodDriverEventHandler.SubscribeForEvent calls GetIOException incorrectly

### ISSUE THREAD

**Issue by jdbruner** [dotnet/iot#1928]
**Describe the bug**

On failure, LibGpiodDriverEventHandler.SubscribeForEvent throws an exception as follows:

```csharp
throw ExceptionHelper.GetIOException(ExceptionResource.RequestEventError, _pinNumber, Marshal.GetLastWin32Error());
```

However, GetIOException is declared as follows:

```csharp
public static IOException GetIOException(ExceptionResource resource, int errorCode = -1, int pin = -1) 
```

The order of the second and third arguments is reversed, resulting in a confusing exception message.

**Steps to reproduce**

This can be verified by inspection of the source code, but if you want a repro procedure, then subscribe to events on a pin that is already in use.

**Expected behavior**

Throw an exception indicating the pin number and error 16 (EBUSY).

**Actual behavior**

Throw an exception indicating pin number 16 and error number equal to the pin number.

**Versions used**

System.Device.Gpio v2.1.0

**Comment by jdbruner** [comment]
I would be (the fix is trivial), but I'm not set up to rebuild it on my machine before submitting the PR.

--John
________________________________

**Comment by pgrawehr** [comment]
@jdbruner Just run the `build.cmd` file in the repository root. I think you need no prerequisites for this.
