### ISSUE TITLE
Nuget links are broken

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/iot#194]
Nuget source links are broken https://www.nuget.org/packages/System.Device.Gpio
![image](https://user-images.githubusercontent.com/7894084/52111770-e67a2500-2604-11e9-8b6b-b24cf3f481eb.png)
But package seems ok
![image](https://user-images.githubusercontent.com/7894084/52112816-fc3d1980-2607-11e9-959b-9f3591240316.png)

**Comment by joshfree** [comment]
@dagood @terrajobst could you give us a quick hand?

**Comment by dagood** [comment]
Poking through your official build, it looks like when @joperezr updated the version of Arcade recently, this problem went away. (Extract the nupkg and look at the nuspec.) I know there was an Arcade issue detecting the URL properly in official builds at some point.

Old packages can't be updated (and I don't think there's a specific exception for URLs), but next release will show the right URL.

**Comment by joperezr** [comment]
This is fixed now.
