### ISSUE TITLE
High-Precision AD HAT For Raspberry Pi, ADS1263 10-Ch 32-Bit ADC

### ISSUE THREAD

**Issue by SSRTC** [dotnet/iot#1955]
I have High-Precision AD HAT For Raspberry Pi, ADS1263 10-Ch 32-Bit ADC. How I can read voltage from channels?

**Comment by pgrawehr** [comment]
Unfortunately, we do not have a binding (driver) for this device yet. 

You need the data sheet (should come with your device or can typically be found online). Alternatively, you can reverse-engineer the existing samples that come with the HAT (most HATs are provided with a python sample). Then you can write your own binding or access the registers directly.
