### ISSUE TITLE
How to work with I2C?

### ISSUE THREAD

**Issue by INTERNALINTERFERENCE** [dotnet/iot#1983]
I use this board: EM3566 (rockchip) and I would like to work with adc. How can I do it?
What I tried: 

```
I2cConnectionSettings settings = new I2cConnectionSettings(1, (int)I2cAddress.GND);
I2cDevice device = I2cDevice.Create(settings);
System.Console.WriteLine("i2c device created");
device.WriteByte(8);
Console.WriteLine("Byte written: " + device.ReadByte().ToString());
```

I got `i2c device created` in console and then I failed with exception:` System.IO.IOException: Error 6 performing I2C data transfer.`

I think it's not a bug. What I do wrong?

**Comment by pgrawehr** [comment]
I don't know that particular board. Do you have detailed information about the I2C bus configuration (e.g. an example in a different language that works, or similar)? 

Also, please check whether your device is available on the expected address by using `i2cdetect -y 1`.
