### ISSUE TITLE
Consider dropping `netstandard2.0` support

### ISSUE THREAD

**Issue by richlander** [dotnet/iot#1986]
I was just working on a binding and needing to workaround the lack of Index/Range support in .NET Standard 2.0. It would be great if we could switch the repo to .NET 6+ targeting.

It seems like we have a few options:

- Status quo.
- Break out the few bindings that we know have utility on .NET Framework into a separate package (that targets .NET Standard 2.0).
- Drop support for .NET Standard 2.0 entirely, and the concrete platforms (like .NET Framework) that are affected by that.

With .NET Core 3.1 going EOL (#1984), now is a great time to have this discussion.

**Comment by raffaeler** [comment]
I already asked this to @joperezr for my serial port branch. 
Also, we are already considering dropping targeting Windows. If this is confirmed, I believe that netstandard2.0 can go away as well.
@Ellerbach You don't need this for the nanoframework, right?

**Comment by joperezr** [comment]
The one reason why we still want to keep NETStandard 2.0 support is in favor of Mono. There are some popular devices where .NET (Core) is not supported yet, for example, the Raspberry Pi Zero. However, some of these do support Mono, so that is where it adds a lot of value to have .NET Standard 2.0.

**Comment by raffaeler** [comment]
Sorry, I forgot that, you are perfectly right (of course).

**Comment by richlander** [comment]
I thought that we had a build of Mono from dotnet/runtime that worked for Armv6 that supported the modern TFMs. Is that right @marek-safar?

**Comment by marek-safar** [comment]
That's correct armv6 is community supported in dotnet/runtime and there are builds (including source build) available for example for Alpine distro.

**Comment by pgrawehr** [comment]
> I thought that we had a build of Mono from dotnet/runtime that worked for Armv6 that supported the modern TFMs.

That confuses me. A build from dotnet/runtime would not be a mono build, would it? That would be a "modern" .NET Core build, right?

I do think we should still support .netstandard2.0 in the upcoming 3.0 release and maybe drop that support in 4.0. See related #1984 for deprecating .netcoreapp3.1.

**Comment by joperezr** [comment]
[Triage]: We discussed this during triage and agreed that probably the best course of action would be to drop netcoreapp3.1 TFM for our next release (3.0), and then look into this issue a bit more to make sure that dropping .NET Standard 2.0 won't break any important scenarios or devices that we care about. If it is decided that this TFM is in fact no longer needed, we will drop it in our next major release (4.0)

**Comment by richlander** [comment]
Sounds like a plan to me.

**Comment by krwq** [comment]
[Triage] We don't have any compelling reason to remove this support. Because of netstandard2.0 we can run on mono. Because of that feels like it's better to do nothing.
