### ISSUE TITLE
Question: Should our sensor binding constructor pass in SpiDevice/I2cDevice or PinNumber ?

### ISSUE THREAD

**Issue by ZhangGaoxing** [dotnet/iot#200]
I think users should avoid touching classes like SpiDevice and I2cDevice, just tell them how to connect the sensor to the host. For example: #193 

SpiDevice need to be set **ClockFrequency** and **SpiMode** , and all of these need to be consulted in the datasheet. For a person who specializes in hardware, he knows how to deal with it. But what should he do for a person who has no hardware knowledge?
```C#
var settings = new SpiConnectionSettings(_busId, _cs)
{
    ClockFrequency = 5000000,
    Mode = SpiMode.Mode3
};
```

**Comment by krwq** [comment]
IMO passing SpiDevice and I2cDevice sounds more convenient. Couple of reasons:
- much easier to pass around settings for anything which wants to build on top
- user has to know busId and cs anyway
- it is possible to swap it with software implementation or mock class
