### ISSUE TITLE
SpiConnectionSettings should have a property for data flow

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#202]
This proposal is to add a data flow property to the SpiConnectionSettings class.

## Rationale and Usage
While most SPI devices us Most Significant Bit (MSB), there are devices that can use Least Significant Bit (LSB). To overcome this today (to my current knowledge) is adding additional software logic to reverse the bits during reads/writes.

## Proposed Changes
The proposed change is to add a new property for data flow.

This could be named `DataLsbFirst` or similar. It could have a default value of false that represents LSB since this is the minority use.  It also doesn't have to be included in the `SpiConnectionSettings` constructor as is similar to other properties like `ClockFrequency`, `Mode`, etc..

```csharp
var spiConnectionSettings = new SpiConnectionSettings(0, 0)
{
    ClockFrequency = 1000000,
    DataLsbFirst= true,
    Mode = SpiMode.Mode0
};
```

## References
- I commented on similar topic in another proposal [Provide a new GpioSpiDevice](https://github.com/dotnet/iot/issues/122).

## Open Questions
1. Windows 10 IoT appears to only allow for MSB.  Is there a way to change this in a system setting or within Windows.Devices.Spi API?
2. It appears you can change this in Linux, but I have not tested.  See https://01.org/linuxgraphics/gfx-docs/drm/driver-api/spi.html.  Need to review if this can be performed programmatically or must be hardcoded in SPI settings.

**Comment by krwq** [comment]
@shaggygi just for reference, do you perhaps know of any specific devices needing this?

**Comment by shaggygi** [comment]
@krwq Reviewing this appears most cases are MSB first, but similar to #201... many processors, APIs and tools appear to be configurable.  So this is one of those areas we might want to support sooner than later.

I came across the following that mentioned it supports LSB first, but didn't dig too much of the details:

- [PS2 Controller](http://roboticsforevery1.blogspot.com/2014/08/interfacing-playstation-controller-with.html)
- [WTV020](https://os.mbed.com/forum/mbed/topic/2170/?page=1#comment-10992)
- [Arduino](https://arduino.stackexchange.com/questions/16348/how-do-you-use-spi-on-an-arduino) This is more of an example for the board and API that allows you to specify the flow.

**Comment by krwq** [comment]
I've opened a PR for both please take a look - naming to be discussed in the PR - I'm not particular fan of name DataFlow but on the other hand I could not come up with anything better. Python calls it `FirstBit` which does not seem good either.

**Comment by shaggygi** [comment]
@krwq how about BitOrder?  Here's [a reference](https://python-periphery.readthedocs.io/en/latest/spi.html) that calls it that.

**Comment by krwq** [comment]
@shaggygi I think I like the DataFlow better than that actually - bit order feels like it is related to numbers not bits in each byte. We will probably be very likely reiterating on the name during code review some time later
