### ISSUE TITLE
Remove .NET Core 3.1 dependencies

### ISSUE THREAD

**Issue by richlander** [dotnet/iot#2043]
We still have multiple uses of `netcoreapp3.1` in our repo. We need to remove it. I don't know how to address all of them. .NET 6 should become our new baseline for concrete TFMs.

https://github.com/search?q=repo%3Adotnet%2Fiot%20netcoreapp3.1&type=code

**Comment by joperezr** [comment]
Thanks for logging this @richlander . Seems like most of the references are irrelevant and should be trivial to remove. Most of it seems to be docs in markdown that points to nca31 output, comments in code for tests (that used to execute on nca31 but don't any more) and the CompatibilitySuppressions which should be re-generated once we ship a new version of the packages.

**Comment by richlander** [comment]
What about this one?

https://github.com/dotnet/iot/blob/c73a9f6ce5d295afb306c9dd492f11af682ba882/eng/common/tools.sh#L437

I'm happy to clean those up. I wasn't sure about the scripts.

**Comment by joperezr** [comment]
We never touch code under `eng\common` folder. All of those are owned by arcade, and so even if we were to make a change to them, changes would be overwritten the next day with the arcade update, so that one we can just skip 😄

**Comment by pgrawehr** [comment]
I think we removed all references to net3.1 with the 3.0 releases. Even the tests are no longer running against net3.1.
