### ISSUE TITLE
Add friendly names for device bindings

### ISSUE THREAD

**Issue by richlander** [dotnet/iot#207]
This README isn't useful for mere mortals looking at the repo to get a sense of what is available who don't have deep understanding of the space.

https://github.com/dotnet/iot/blob/master/src/devices/README.md

For example, "BMP280" could be updated to "BMP280 -- Digital Pressure Sensor", which happens to exactly match the datasheet.

**Comment by joperezr** [comment]
That mames sense. I was thinking of dividing the list into sections by functionality but this would be a good first step.

**Comment by richlander** [comment]
Fixed: https://github.com/dotnet/iot/commit/8ce4e3da2b8690dab1144dc87626ea4bf2f5e427
