### ISSUE TITLE
Adding Source code to Project Errors

### ISSUE THREAD

**Issue by Smurfj3** [dotnet/iot#2072]
If I add the source code as a new project to my WPF application, I get the following errors:

![00d9bd64baf393b1d5e8ef77b054196e-png](https://user-images.githubusercontent.com/48727967/234606789-6e806ee9-7fe5-4ce6-ab6f-6500a885d277.jpg)

**Comment by pgrawehr** [comment]
Can you explain why you would want to include the _source code_ directly in your project? Just reference the nuget file. 

On the other hand, the error indicates that you have some problems with accessing the nuget server. Do you have any strange `Nuget.config` files in your project?

**Comment by Smurfj3** [comment]
I was trying to get it to work in Xamarin Forms, but with the Nuget file there are a few Windows related errors, I was trying to see if those things were necessary to run in Xamarin Forms.

**Comment by Smurfj3** [comment]
![a0ec1085bf07b77f5b8eff32ffb614d8](https://user-images.githubusercontent.com/48727967/236195671-c246963a-09bb-4162-a385-299658de09ef.png)

Those are the errors I get as soon as I reference the Nuget File. 

This is not going to be used on a phone, it's actually Android installed on an Orange Pi 5, which I am aware there is no driver support for the Orange Pi 5 yet, I see someone else actually requested it. I am hoping it will be added soon or I am going to have to look at how it works exactly, so I can add it myself. As far as I am aware there is already Rockchip driver and just need to find the GPIO pin offset and do the mapping, I just haven't really looked into how that works and what it means if you make mistakes, not planning on frying my Orange Pi 5.
