### ISSUE TITLE
Orange PI 5 GPIO driver

### ISSUE THREAD

**Issue by SidineiSantosSousa** [dotnet/iot#2073]
Is there any prediction of when the driver for the Orange Pi 5 will be available?

I thought the Orange Pi 5 was great and would like to use it with Dotnet IoT :(.

**Comment by krwq** [comment]
[Triage] As soon as somebody contributes 😄 cc: @Ellerbach @ZhangGaoxing

**Comment by krwq** [comment]
Closing as duplicate of https://github.com/dotnet/iot/issues/2066

**Comment by ZhangGaoxing** [comment]
I currently do not have the board for RK3588s and it is slightly expensive😅
