### ISSUE TITLE
CpuTemperature throwing 'System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode.' on read

### ISSUE THREAD

**Issue by PRIMETSS** [dotnet/iot#2122]
On Manjaro Linux running on RiPi 3B attempt to read the Cpu Temperature causes a exception to be thrown

'Unhandled exception.Unhandled exception.  System.TypeInitializationException: The type initializer for 'UnitsNet.UnitAbbreviationsCache' threw an exception.
 ---> System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.'

Happens with or without environment variable set export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT='1'

`if (((LCDStatusDisplay)state).CpuTemperature.IsAvailable)
                        WriteLine(((LCDStatusDisplay)state), $"CPUTemp: {((LCDStatusDisplay)state).CpuTemperature.Temperature}");`

```
Using: 
Linux version 6.1.37-1-MANJARO-ARM-RPI (builduser@gitlab-runner-ampere-cax41) (gcc (GCC) 12.1.0, GNU ld (GNU Binutils) 2.38) #1 SMP PREEMPT Mon Jul  3 12:19:05 UTC 2023

Iot.Device.Bindings v3.0.0.0

.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     manjaro-arm
 OS Version:
 OS Platform: Linux
 RID:         linux-arm64
 Base Path:   /home/paul/.dotnet/sdk/7.0.202/

Host:
  Version:      7.0.4
  Architecture: arm64
  Commit:       0a396acafe

.NET SDKs installed:
  7.0.202 [/home/paul/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.4 [/home/paul/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.4 [/home/paul/.dotnet/shared/Microsoft.NETCore.App]

**Comment by krwq** [comment]
[Triage] Can you provide how you build and run the app and if the environment where you're running is different than where you're building also provide `dotnet --info` for that environment. We're curious if you're trimming the executable. We haven't seen similar error anywhere
