### ISSUE TITLE
suggest make this method protected

### ISSUE THREAD

**Issue by HumJ0218** [dotnet/iot#2138]
https://github.com/dotnet/iot/blob/c80f9988b8ad95e96a096543caa15fbb3c58f0a2/src/devices/Is31fl3731/Is31fl3731.cs#L190

in order to facilitate the subclasses in implementing a one-time update of all pixel states.

**Comment by krwq** [comment]
Are you planning to add new device binding? If so feel free to change that in that PR if it's needed.
