### ISSUE TITLE
AIS Manager is not properly calculating safety information

### ISSUE THREAD

**Issue by pgrawehr** [dotnet/iot#2143]
The AisManager is not properly taking the own position into account to calculate the CPA and TCPA values (closest point of approach and time to closest point of approach). Also, it uses a wrong time for extrapolating the vessel positions.

This has the impact that warnings about close encounters are not properly generated and distances between vessels are calculated incorrectly, often giving unreasonably large CPA values. 

A fix is being worked on.

**Comment by krwq** [comment]
[Triage] we should edit README pages for all devices and this particular device to create a statement about the safety
