### ISSUE TITLE
GPIO driver should add batch write and read function

### ISSUE THREAD

**Issue by HumJ0218** [dotnet/iot#2147]
Although `GpioController` provides `Write(ReadOnlySpan<PinValuePair> pinValuePairs)` for batch writes, the actual implementation is still written one by one.

This may prevent some GPIO controllers from operating multiple IO ports at the same time, resulting in the actual single write of the corresponding ports still changing one by one, resulting in inefficient communication and hardware performance that does not match expectations.

Is it possible to add true bulk read-write methods to GpioController and GpioDriver to improve communication efficiency where possible?

**Comment by pgrawehr** [comment]
As some drivers already support that, I guess this should be quite easy to do. Just move `protected virtual void Write(ReadOnlySpan<PinValuePair> pinValuePairs)` to `GpioDriver` and call that directly from the GpioController. Then it can be overwritten.
