### ISSUE TITLE
Build fails running Build.cmd at RGBLedMatrix/samples/Program.cs - CS4014

### ISSUE THREAD

**Issue by fehdem** [dotnet/iot#2149]
**Describe the bug**
Build fails running Build.cmd at RGBLedMatrix/samples/Program.cs(66,1)
`error CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
`
**Steps to reproduce**
Running Build.cmd on Windows command line.

Dotnet --version: 7.0.401
(instead of 7.0.203 as configured in the most recent global.json)

**Comment by krwq** [comment]
I've sent a patch, it will also remove the need to touch global.json
