### ISSUE TITLE
ILi9341 on Raspberry Pi 4

### ISSUE THREAD

**Issue by alberk8** [dotnet/iot#2181]
**Describe the bug**

I am trying out the code snippet on the [Readme](https://github.com/dotnet/iot/blob/74f56fae18917dd20379254e76dc21ae1c69e52c/src/devices/Ili934x/README.md) and could not get it to compile.  

**Steps to reproduce**

```csharp
// put sample code here
```

**Expected behavior**
Expect it to run on Raspberry Pi 4.

**Actual behavior**

**Versions used**
dotnet 6.0 SDK
Latest Nuget

**Comment by Ellerbach** [comment]
@alberk8 have you tried the sample itself?

https://github.com/dotnet/iot/blob/74f56fae18917dd20379254e76dc21ae1c69e52c/src/devices/Ili934x/samples/Program.cs

All compiles otherwise, we can't merge! So I'll be surprised if it's broken. Maybe the readme is not up to date indeed

**Comment by alberk8** [comment]
@Ellerbach,

I managed to get the TFT screen to light up and working but I have this issue with the link that you have provided.  The line causing the issue [this](https://github.com/dotnet/iot/blob/74f56fae18917dd20379254e76dc21ae1c69e52c/src/devices/Ili934x/samples/Program.cs#L31).   Otherwise the FillRect works.

```
Unhandled exception. System.InvalidOperationException: No image factory registered. Call BitmapImage.RegisterImageFactory() with a suitable implementation first. Consult the documentation for further information
   at Iot.Device.Graphics.BitmapImage.VerifyFactoryAvailable()
   at Iot.Device.Graphics.BitmapImage.CreateBitmap(Int32 width, Int32 height, PixelFormat pixelFormat)
   at Iot.Device.Ili934x.Ili9341.GetBackBufferCompatibleImage()
```

**Comment by Ellerbach** [comment]
@pgrawehr you may want to have a look at this one

**Comment by pgrawehr** [comment]
I'm quite sure I have tested this (and it would be really bad if SkiaSharp wouldn't work on the RPI). I'll give it another try as soon as possible. 

Make sure you call `SkiaSharpAdapter.Register()` at the beginning of your application, that should fix the above exception.
