### ISSUE TITLE
 logical GPIO

### ISSUE THREAD

**Issue by XiaoBaiXJ** [dotnet/iot#2284]
My logical GPIO pins are more than 32, but when I run the code and input a number greater than 32, the system reports an error. Why is this happening?

**Comment by Ellerbach** [comment]
Can you please give more details on which board you are using, the driver used, and any other information that can help understaing your issue?

**Comment by XiaoBaiXJ** [comment]
In an ARM64 environment with .NET 7, attempting to use a GPIO logical pin number greater than 31 results in a warning that the pin is not found
/
![Uploading 微信图片_20240227100239.png…]()

**Comment by Ellerbach** [comment]
Can you please give us details? You tried to upload a picture which has not been uploaded.
And also please give details about the hardware, the driver you are using, what is installed

**Comment by XiaoBaiXJ** [comment]
![pic](https://github.com/dotnet/iot/assets/44961186/62f306bf-f78e-4bd8-aac9-d61da6ad2991)
Use .Net7 ARM64

**Comment by XiaoBaiXJ** [comment]
If the input GPIO logical port exceeds 31, the system will report an error with a "Segmentation fault".
