### ISSUE TITLE
UltralightCardType detect bug

### ISSUE THREAD

**Issue by huangmagyc** [dotnet/iot#2285]
I have nfc sticker, this chip is NTAG216,i trying PN532 and initialize UltralightCard then UltralightCardType enum shows unknown.
I view UltralightCard constructor , about NTAG216 card type check by GetVersion bytes may be not right.

this version 3.1 code 
```csharp
//...
else if ((Data[2] == 0x04) && (Data[3] == 0x01) && (Data[4] == 0x01) && (Data[5] == 0x00) && (Data[6] == 0x13))
{
    NdefCapacity = 888;
    UltralightCardType = UltralightCardType.UltralightNtag216;
}
//...
```

the NTAG216 GetVersion bytes[3] is right to 0x02 
```csharp
//...
else if ((Data[2] == 0x04) && (Data[3] == 0x02) && (Data[4] == 0x01) && (Data[5] == 0x00) && (Data[6] == 0x13))
{
    NdefCapacity = 888;
    UltralightCardType = UltralightCardType.UltralightNtag216;
}
//...
```

**Comment by Ellerbach** [comment]
Correct, just checked here: https://www.nxp.com/docs/en/data-sheet/NTAG213_215_216.pdf
Table 28:
![image](https://github.com/dotnet/iot/assets/8145578/969bd24d-5ebf-4738-a831-7b054c442b8f)

PR welcome if you want to fix it! I4ll be happy to approve and review it. While you'll be there, please check that the 2 others are correct :-)
