### ISSUE TITLE
IOT device tests should use MOQ for testing

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/iot#231]
Using a mocking framework will make tests more robust and easier to follow as frameworks allow easier expressing of intent over making manual mocks.

MOQ is the standard: https://github.com/moq/moq4

Starting Guidelines:

1. _Prefer_ to use MOQ to generate mocks
2. _Prefer_ strict mode mocking (calls to non mocked API throw)

@krwq, @joperezr, @shaggygi

**Comment by JeremyKuhne** [comment]
Note: In my first attempt to use this I can't seem to get MOQ to work with `Span<>`. I'm not finding any info on how to set that up. The generated proxy throws an `InvalidProgramException` with `Cannot create boxed ByRef-like values.` when trying to mock `SpiDevice` and call `Write()` on it.

**Comment by joshfree** [comment]
@ahsonkhan

**Comment by Ellerbach** [comment]
We have quite some examples in the tests where I2C, SPI devices are mocked. That may be enough as, correct, Span<> can't be mocked.

**Comment by krwq** [comment]
[Triage] We should talk about this more and decide on the direction

**Comment by krwq** [comment]
[Triage] let's close this - it's not actionable for now
