### ISSUE TITLE
Package 'System.Text.Json' 6.0.9 has a known high severity vulnerability

### ISSUE THREAD

**Issue by ganeshskhatri** [dotnet/iot#2365]
Giving a warning "Package 'System.Text.Json' 6.0.9 has a known high severity vulnerability" in .net 9.0.

**Comment by raffaeler** [comment]
Thank you for raising this.
You can currently resolve the vulnerability in your app by directly adding a reference to the most recent (non-vulnerable) `System.Text.Json` package.
As soon as you add the direct reference, the build should not give you the warning anymore.

**Comment by pgrawehr** [comment]
Closing this issue as it has already been fixed on master by #2357
