### ISSUE TITLE
Add Ws2808 LED driver binding  - Refactoring existing Ws2812B bidning

### ISSUE THREAD

**Issue by DemoS76** [dotnet/iot#257]
Add binding for Ws2808 LED driver
[https://datasheetspdf.com/pdf-file/806051/Worldsemi/WS2801/1](url)

**Comment by joperezr** [comment]
@DemoS76 if you are interested in taking this, let us know if there is anything we can help you out with

**Comment by DemoS76** [comment]
Hi, I've finished with it. Thanks.
