### ISSUE TITLE
Iot.Device -> Iot.Thing?

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#258]
Should we rename Device to Thing? Since IOT is internet of things and not devices.

cc: @richlander

**Comment by joshfree** [comment]
IoT.Thing sounds a bit redundant (Internet of Things Things)

**Comment by joperezr** [comment]
Device kind of sounds better to me as well, but that is probably just because I’m used to thinking of them as devices. I don’t have strong feelings against either option.

**Comment by krwq** [comment]
I was thinking of 2 namespaces under Iot:
- Thing - devices/sensors
- Net - protocols and way of describing how things to talk to each other

**Comment by joshfree** [comment]
I'm not super worried about the name right now given we only have two dozen device bindings under our belt.  I think we'll rename and refactor the namespaces and source code directory structure several times while this project is in the preview phase.

**Comment by krwq** [comment]
Closing this issue then as won't fix and we can reiterate later
