### ISSUE TITLE
Expose public GpioController methods on IGpioController

### ISSUE THREAD

**Issue by matthewethomas** [dotnet/iot#260]
Please consider adding the following methods to IGpioController. These are all already public methods on `GpioController`'s implementation and will add functionality that is present on the implementation, but missing on the interface.

Pin status/inquiry methods:
---
```C#
PinMode GetPinMode(int pinNumber);
bool IsPinOpen(int pinNumber);
bool IsPinModeSupported(int pinNumber, PinMode mode);
```

Wait methods:
---
```C#
WaitForEventResult WaitForEvent(int pinNumber, PinEventTypes eventTypes, CancellationToken cancellationToken);
ValueTask<WaitForEventResult> WaitForEventAsync(int pinNumber, PinEventTypes eventTypes, CancellationToken token);
```

Callback methods:
---
```C#
void RegisterCallbackForPinValueChangedEvent(int pinNumber, PinEventTypes eventTypes, PinChangeEventHandler callback);
void UnregisterCallbackForPinValueChangedEvent(int pinNumber, PinChangeEventHandler callback);
```

**Comment by joperezr** [comment]
This makes sense, although it might be a little complex to implement the eventing methods for some Gpio providers like the MCP devices, @JeremyKuhne any ideas how difficult would that be? I suppose that in some cases where eventing is not supported we might have to do polling on the values to detect changes?

That said, I guess worst case scenario we could have those devices where implementing this is not trivial to simply throw not supported in this case.

**Comment by shaggygi** [comment]
You would probably need to poll the interrupt related port bits or could wire up the INTA/B pins.

**Comment by shaggygi** [comment]
We probably should add `PinCount` property, as well.

```csharp
/// <summary>
/// The I/O pin count of the device.
/// </summary>
public int PinCount { get; }
```

**Comment by JeremyKuhne** [comment]
Related to #295.

These seem like no brainers, I just didn't add them right out of the gate as I didn't need them to solve my immediate problem. 

``` C#
public int PinCount { get; }
PinMode GetPinMode(int pin);
bool IsPinOpen(int pin);
bool IsPinModeSupported(int pin, PinMode mode);
```

Events I'm not so sure about. I'm not sure all devices have the ability to do this in a rational way. If we do add them we'd want some way of tracking whether or not it is possible, is hardware/polling driven, etc.

**Comment by joperezr** [comment]
This is approved for everything but Eventing methods. Eventing methods we need to discuss a bit more if we want them part of the interface and simply throw Not Supported on devices that can't deal with this, or to not have them. Flagging as up-for-grabs.

**Comment by matthewethomas** [comment]
Awesome!
