### ISSUE TITLE
Potential memory leak due to CancellationTokenSource

### ISSUE THREAD

**Issue by CosminLazar** [dotnet/iot#276]
While browsing through the source code of GpioController.cs I could see it makes use of CancellationTokenSource without actually disposing it. From what I can see in the source code of CancellationTokenSource it does not have a finalizer (https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Threading/CancellationTokenSource.cs), therefore its Dispose method will never be called.

To make it clear, I have not observed an actual memory leak, I just reviewed the code.
The places that make use of the CancellationTokenSource without disposing it are:
-https://github.com/dotnet/iot/blob/724c8dc7102a1a95e1d70b860b2ad4b3c213387d/src/System.Device.Gpio/System/Device/Gpio/GpioController.cs#L204
-https://github.com/dotnet/iot/blob/724c8dc7102a1a95e1d70b860b2ad4b3c213387d/src/System.Device.Gpio/System/Device/Gpio/GpioController.cs#L234

If time allows I will try to look more into the issue, otherwise I am just letting you know about it.

**Comment by sharwell** [comment]
CancellationTokenSource will only leak if it was created with CreateLinkedTokenSource. With that said, it's still a good idea to call Dispose appropriately.

**Comment by CosminLazar** [comment]
True, a bad experience with the linked token source must be why I got the alarm in my head when I saw the CancellationTokenSource not being disposed. Furthermore, today I learned that apparently not disposing the CancellationTokenSource can also lead to performance issues https://twitter.com/davidfowl/status/1050278811558850560?lang=en

**Comment by krwq** [comment]
@CosminLazar do you feel like sending PR with the fix? We should be disposing it regardless if it will leak or not

**Comment by CosminLazar** [comment]
Sure, here it is https://github.com/dotnet/iot/pull/281
