### ISSUE TITLE
Add bindings for multimedia abstraction layer (i.e. MMAL, includes Camera/Audio)

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#287]
We currently need way of using camera and audio.

One way to provide that is to re-use MMAL effort which allows to access both. It is also used by projects like https://github.com/waveform80/picamera (docs at: https://picamera.readthedocs.io/en/release-1.13/).

We will need to figure out if we want to go even lower with the abstraction or if this is a right spot.

Documentation: http://www.jvcref.com/files/PI/documentation/html/

There is a C# effort already - perhaps makes sense to reuse
https://github.com/techyian/MMALSharp - I've quickly tried it at home but haven't had success (no errors, no expected output)

cc: @joshfree @richlander

**Comment by krwq** [comment]
cc: @ZhangGaoxing

**Comment by mtripsky** [comment]
Is somebody working on this? I would like to help with this

**Comment by joperezr** [comment]
I'm not aware of anybody working on this. @ZhangGaoxing added some support for Video on PR #664 but that is just a part of this, so it would be great if you want to contribute with this 👍

**Comment by joperezr** [comment]
I'll go ahead and assign you for now, feel free to ask as many questions as you need.

**Comment by Ellerbach** [comment]
I feel this is addressed by https://github.com/dotnet/iot/tree/master/src/devices/Media. @krwq maybe we can close this one?
