### ISSUE TITLE
Utilizing C# 8.0 Features

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#300]
Understanding it is a little ways off, I wanted to start a thread to gather thoughts around how this repo uses features provided in C# 8.0 (e.g. nullable reference types, etc.).  Also, I noticed we are using different values for LangVersion in projects.  This might be a good time to provide details on what to use, as well.

**Comment by krwq** [comment]
I think using latest or later (latest means latest stable). I think we should make repos default to latest but single projects should be able to use also experimental features if it makes sense
