### ISSUE TITLE
Sysfs driver pin numbering offset is different for arm64

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/iot#343]
Sysfs driver was not working in 64 bit Debian for raspberry pi. Recently find out offset numbering of gpio pins start from 458, so for example if you want to access pin 18 you need to use 458 + 18 = 476. Need to find a way to determine and set offset pin numbering withing driver so that users could use consistent numbering.  https://wiki.debian.org/RaspberryPi3

**Comment by joperezr** [comment]
This needs to be fixed for 3.0. Should be easy enough to fix. Flagging as up-for-grabs since @buyaa-n won't have time to look at this any time soon. If no one else picks this up, either her or me can pick this one.
