### ISSUE TITLE
Provide ARM64 assets in System.Device.Gpio

### ISSUE THREAD

**Issue by richlander** [dotnet/iot#351]
The NuGet package only has 32-bit assets for ARM. It should also contain assets for ARM64.

I'm assuming separate assets are needed for musl, to support Alpine ARM64. We should validate that at the same time.

**Comment by joshfree** [comment]
@joperezr PTAL

**Comment by joperezr** [comment]
yup I'll take care of this.

**Comment by joperezr** [comment]
This has been fixed since we now PInvoke to libgpiod.so directly so we don't need the extra shim. I have validated that libgpiod driver works for arm64 in the RaspberryPi 3.
