### ISSUE TITLE
Add Mcp3428 ADC bindings

### ISSUE THREAD

**Issue by kmate95** [dotnet/iot#353]
4 channel ADC chip with I2C interface. Datasheet here: http://ww1.microchip.com/downloads/en/DeviceDoc/22226a.pdf
I'm currently working on it. Gonna make PR when I have time to finish it.

**Comment by joshfree** [comment]
Thank you for the (future) contribution @kmate95 😄

**Comment by krwq** [comment]
Closing this since PR is merged. Please let me know if there is anything left.
