### ISSUE TITLE
Mono WinForms + dotnet/iot GPIO Demo with Torizon

### ISSUE THREAD

**Issue by microhobby** [dotnet/iot#359]
This is not an issue!
I would like to share with you a video of a demonstration I made using dotnet/iot running on a Toradex Colibri iMX7D 1GB in a Torizon container (Toradex docker ready platform for your computers on modules)

I'm using dotnet/iot with LibGpiodDriver and accessing two GPIO banks from iMX7:

[![Youtube video](https://img.youtube.com/vi/1d3g2VDZyXE/0.jpg)](https://www.youtube.com/watch?v=1d3g2VDZyXE)

**Comment by joperezr** [comment]
That is awesome thank you so much for sharing this @microhobby!

cc: @richlander check out the demo!

**Comment by joshfree** [comment]
Thanks for sharing @microhobby 😃
