### ISSUE TITLE
Add Hummidity and Compensate Hummidity to the BME280 device binding.

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [dotnet/iot#399]
For BME280, you can read the pressure and the temperature (including compensate values) but so far there's nothing for humidity. Any chance for this to be implemented please?

**Comment by joperezr** [comment]
@MarkCiliaVincenti Adding this shouldn't be too hard, any chance you want to take a stab at it 😄 ? We are happy to guide you and help you with any questions that you may have.

**Comment by MarkCiliaVincenti** [comment]
> @MarkCiliaVincenti Adding this shouldn't be too hard, any chance you want to take a stab at it 😄 ? We are happy to guide you and help you with any questions that you may have.

It's not as easy as one would think. There's a lot of stuff added onto BME280 over BMP280 so some architectural changes are needed to accommodate them, not just a case of adding a couple of methods to the Bme280 class.

**Comment by joperezr** [comment]
mm I'm not sure I follow. If this functionality is strictly only for Bme280 class, then it should just be adding a couple of methods to that file, you shouldn't need to touch BMP280 as that class won't have this functionality.

**Comment by MarkCiliaVincenti** [comment]
> mm I'm not sure I follow. If this functionality is strictly only for Bme280 class, then it should just be adding a couple of methods to that file, you shouldn't need to touch BMP280 as that class won't have this functionality.

It's not just a case of adding methods. BME280 requires a vaster CalibrationData.cs and a vaster Register.cs. It depends on what architecture path you want to take. Do you completely separate the two or do you do base classes for CalibrationData and Register classes too?

**Comment by joperezr** [comment]
Oh I see now, that makes sense. It would take a bit of refactoring I guess to have that work, since you would have to set the calibration data on each individual class. The register classes don't need to change IMO, since it's fine if one of the registers in the enum is not used by one of the classes.

**Comment by kurtnelle** [comment]
You can borrow code from my project https://github.com/kurtnelle/BME280Logger or monoculture's project to get the humidity logic.
