### ISSUE TITLE
Update Generic Unix Device Driver to use libgpiod when available instead of sysfs calls

### ISSUE THREAD

**Issue by joshfree** [dotnet/iot#42]
https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/README

> libgpiod
> ========
> 
>   libgpiod - C library and tools for interacting with the linux GPIO
>              character device (gpiod stands for GPIO device)
> 
> Since linux 4.8 the GPIO sysfs interface is deprecated. User space should use
> the character device instead. This library encapsulates the ioctl calls and
> data structures behind a straightforward API.
> 
> RATIONALE
> ---------
> 
> The new character device interface guarantees all allocated resources are
> freed after closing the device file descriptor and adds several new features
> that are not present in the obsolete sysfs interface (like event polling,
> setting/reading multiple values at once or open-source and open-drain GPIOs).
> 
> Unfortunately interacting with the linux device file can no longer be done
> using only standard command-line tools. This is the reason for creating a
> library encapsulating the cumbersome, ioctl-based kernel-userspace interaction
> in a set of convenient functions and opaque data structures.

https://blog.adafruit.com/2018/11/26/sysfs-is-dead-long-live-libgpiod-libgpiod-for-linux-circuitpython/

> With more linux boards coming out with GPIO (there’s probably 4 more released since we wrote this post) – having a consistent, reliable, complete GPIO interface is pretty important to avoid icky unmaintainable code. So we’re pretty psyched about libgpiod. From our experiments, its much much faster than sysfs. Its not as fast as mem twiddling, but that’s not too surprising, there’s still kernel messages and error checking done. A Pi 3 got us 400Khz pin output toggles in a loop in C, 100KHz in Python examples, and that’s pretty good for bitbanging. (For SPI or I2C, use the hardware peripherals, they can go multi-MHz and can be shared between processes!)

> and has the benefit of being forward compatible with any other Linux board that runs a 4.8+ kernel.

**Comment by buyaa-n** [comment]
It is implemented with https://github.com/dotnet/iot/pull/219
