### ISSUE TITLE
Get current PinValue of output pin

### ISSUE THREAD

**Issue by erikmf12** [dotnet/iot#466]
I would like to be able to get the value of a pin set for output. I know you can't 'read' from an output, but the controller could save the pinvalues of open pins set to output, and whether they're set high or low. Is this something that would be useful in these classes or would this logic best be kept in calling code?

**Comment by shaggygi** [comment]
This appears to be a duplicate of #183.  If you can, please add notes on that thread and close this issue.  Thx

**Comment by erikmf12** [comment]
@shaggygi  Sorry, I missed them talking about actually reading an output pin - I stopped when I read 'it isn't possible'.
