### ISSUE TITLE
.Net Core on Raspberry Pi 3 A+

### ISSUE THREAD

**Issue by JawadJaber** [dotnet/iot#491]
It is [stated](https://github.com/dotnet/iot/tree/master/samples) that .Net Core does not work on RP models A. But as per [this](https://www.modmypi.com/blog/raspberry-pi-comparison-table), RP model 3A+ is with ARMv8-A which is same as RP 3B model. So please confirm or revise the page if necessary.

**Comment by joperezr** [comment]
@JawadJaber thanks for catching that, do you have a Pi 3A+? We don't currently have one to test with, so if you have validated that .NET Core runs well on it then we can go and fix the docs so that we mention that A+ should also work.

**Comment by shaggygi** [comment]
@joperezr I purchased one of these a few weeks back, but never got around setting up.  I installed Raspbian tonight and was able to write values using DeviceApiTester with GPIO commands.  I haven't tried other types like I2C and SPI yet, but I'd bet those work, as well.  I'll try to do some basic write tests with those this weekend to double-check.

**Comment by JawadJaber** [comment]
@joperezr I ordered Pi 3A+ and is not delivered yet, I have dotnet core that is under production with Pi 3B, 3B+. Once received, I will deploy my dotnet core for testing and inform you.

**Comment by joperezr** [comment]
@shaggygi @JawadJaber thanks so much to both of you for checking. Once you confirm I'll go ahead and update our docs. The fact that .NET Core runs fine for @shaggygi makes me think that there shouldn't be any problems but it would be great to just double check I2C and SPI if possible 😄

**Comment by krwq** [comment]
Raspberry Pi 3 A+ work correctly on my PIs.

**Comment by joperezr** [comment]
Great, I'll leave this open though in order to track the change in the docs to say we do work there properly.
