### ISSUE TITLE
TCA9548 Low-Voltage 8-Channel I2C Switch

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#508]
The TCA9548 is basically an I2C multiplexer that branches out to more I2C buses.
**Datasheet**: http://www.ti.com/lit/ds/symlink/tca9548a.pdf

**Comment by shaggygi** [comment]
There's more devices in the family, so structure appropriately. 

https://www.nxp.com/docs/en/application-note/AN262.pdf

**Comment by krwq** [comment]
[Triage] It's already added https://github.com/dotnet/iot/tree/main/src/devices/Tca954x
