### ISSUE TITLE
Change polling mechanism to use poll instead of epoll

### ISSUE THREAD

**Issue by joperezr** [dotnet/iot#52]
per @stephentoub in https://github.com/dotnet/iot/pull/45#pullrequestreview-179874241

>This is called the "unix" driver, but many unixes don't have epoll, e.g. macOS, FreeBSD, etc. They have an alternate mechanism called kqueues.
I'm also unclear why we're using epoll rather than just poll (which does exist everywhere). epoll is intended for scalability, where you need to wait for / listen to events on lots of file descriptors at once (hundreds, thousands, etc.); it doesn't really provide any benefits, just complexity, when listening for events on one or even a couple. Is there a reason we can't just use poll? Does epoll actually do something special for the file descriptors in question?

**Comment by krwq** [comment]
[Triage] Closing: epoll seem more generic and allows us to do optimization in the future, there doesn't seem to be any gain of using poll. This is only used in SysFsDriver anyway and it's not a preferred implementation anyway. Also we currently don't support SysFs on OSX
