### ISSUE TITLE
SetPinMode IsPinModeSupported for RaspberryPi3Driver does nothing

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#536]
Came across this today, but have not reviewed on what it should do.

SetPinMode method calls IsPinModeSupported, but doesn't do anything whether it is true/false.

https://github.com/dotnet/iot/blob/833728c8f7dedf4b5699a5c93863eb7a9ab2f155/src/System.Device.Gpio/System/Device/Gpio/Drivers/RaspberryPi3Driver.Linux.cs#L163

**Comment by krwq** [comment]
looks like a bug, probably should be:
if (!IsPinModeSupported(...))
  throw new ArgumentException(nameof(mode));

or perhaps NotSupportedException, not sure

**Comment by shaggygi** [comment]
Yeah, I found another area that calls this and throws if false.
