### ISSUE TITLE
Proper way to comment constructor

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#565]
I came across this topic and wasn't sure if we should be doing similar in this repo.

https://stackoverflow.com/questions/6868138/whats-the-proper-way-to-comment-a-constructor-in-a-generic-class

Currently...

```csharp
/// <summary>
/// Initializes new instance of SpiConnectionSettings.
/// </summary>
/// <param name="busId">The bus ID the device is connected to.</param>
/// <param name="chipSelectLine">The chip select line used on the bus.</param>
public SpiConnectionSettings(int busId, int chipSelectLine)
```

Should the summary be...

```csharp
/// <summary>
/// Initializes a new instance of the <see cref="SpiConnectionSettings"/> class.
/// </summary>
/// <param name="busId">The bus ID the device is connected to.</param>
/// <param name="chipSelectLine">The chip select line used on the bus.</param>
public SpiConnectionSettings(int busId, int chipSelectLine)
```

**Comment by krwq** [comment]
@shaggygi if you mean `<see cref="SpiConnectionSettings"/>` then ideally yes but better not to have it than have no doc at all

**Comment by shaggygi** [comment]
Okay.  Just checking what the norm is as if it was preferred I could do a PR to update throughout in this format.  Lemme know and I can allocate some time.

cc: @joperezr

**Comment by joperezr** [comment]
Yes, as @krwq mentions idieally we would like to have `cref` like documentation. We will eventually want to upload all of our comments (for System.Device.Gpio) to MSDN docs, where they will be audited and so suggestions like using cref will be pointed out, so getting  ahead of them would be great 😄

**Comment by shaggygi** [comment]
@joperezr sounds good.  i'll try to do a first round of this over the weekend.
