### ISSUE TITLE
Issue with PR Add MCP3428 Bindings. #353

### ISSUE THREAD

**Issue by Frankenslag** [dotnet/iot#572]
@kmate @krwq

 Just tried a build of the latest repository,

 I get a failures of :- 

`error CS0234: The type or namespace name 'Drivers' does not exist in the namespace 'System.Device.I2c' (are you missing an assembly reference?)`

and 

`Error	CS0246	The type or namespace name 'UnixI2cDevice' could not be found (are you missing a using directive or an assembly reference?)	D:\source\dotnet\iot\build.proj	D:\source\dotnet\iot\Mcp3428.Sample.cs
`

I believe that this is because some of the namespaces have been changed and devices refactored.

Please see below for a proposed fix (builds but otherwise untested) but I haven't submitted a PR as this is such a new change that thought that perhaps you might want to do it.

![image](https://user-images.githubusercontent.com/12005779/60754651-137b9b00-9fdc-11e9-9d12-2a2a2cd0619f.png)

**Comment by krwq** [comment]
Already fixed https://github.com/dotnet/iot/pull/571
