### ISSUE TITLE
Remove the RuntimeIdentifier from all of our P2Ps

### ISSUE THREAD

**Issue by joperezr** [dotnet/iot#623]
Currently, all of our ProjectReferences to System.Device.Gpio require to pass in a RuntimeIdentifier set to Linux. This is because if you don't pass any RuntimeIdentifier, we currently perform a multiplexing build that will generate both the windows and linux assets. Ideally, we would want to have a way of just asking for getting the reference assembly, so should have this in the future. In the meantime, we pass in the runtime identifier in order to use the linux implementation as the reference assembly, since that configuration is the one we use to actually produce the ref.

**Comment by Frankenslag** [comment]
@joperezr @krwq 

This, along with #622 has been applied to the PR for the Ssd1351 Binding #575
