### ISSUE TITLE
[Proposal] Move device projects to respective vendor folder

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#63]
/cc @joperezr @richlander 

I'm currently reviewing and trying to clean up some of the code for the Mcp3008 project and think it would be a good idea to come up with some better structuring regarding IoT devices folder.  This might be a good topic to add in doc related to #55.

If we begin to have a "rich set" of many component bindings, it could get messy quick.  I propose we at least have a `vendor` (or similar) folder that separate components.  Yes, some manufacturers produce the same component sometimes, but most are differentiated and the links/specs usually come from the creator of said components.

For example, the MCP3008 is a Microchip component.  Therefore, it would be good to place its related projects (API, tests, etc.) under the `dotnet\iot\devices\vendor\Microchip` (or similar) folder.

I've seen a few places where peeps reference components like Adafruit [component] for example.  This is not necessarily correct as Adrafruit is a distributor, but provides [code examples](https://www.adafruit.com/product/856).  There might be times they (Adafruit, Sparkfun, etc.) create their own component (maybe a combination of other components).  In this case, there would be a specific folder for their components.  Using #12 as an example, we could have a  `dotnet\iot\devices\vendor\Adafruit\PiOLED` folder.

To elaborate a little further...  Adrafruit offers a [breakout board](https://www.adafruit.com/product/2717) for the [TCA9548A](https://cdn-shop.adafruit.com/datasheets/tca9548a.pdf).  This component is produced by Texas Instrument.  The breakout board is basically an easy way for hobbyists to connect to controller boards.  So in this case, we could have `dotnet\iot\devices\vendor\TexasInstruments\TCA9548A` (or similar) folder.  This API should be able to work for Adrafruit's breakout board and where others use said component in other hardware boards.

One problem with labeling to specific vendor folders is [acquisitions do occur from time to time](https://www.microchip.com/investor/Announcement/MCHP%20to%20Acquire%20Microsemi%20Corporation.030118.pdf).  However, transitions are usually long and most of the time they keep the branding.  Engineers are usually smart enough to know the difference and how to find specs.  If the vendors' name is not included in project namespace, it shouldn't be a breaking change in code... just a new folder location in repo. 

Does this make sense?  What are thoughts around this?  I know I'm not thinking of all scenarios.  Just trying to collect some ideas to make a better ecosystem related to this repo while it's still young.

Thx

**Comment by joshfree** [comment]
While we can organize by vendor; I would vote to start out initially by structuring the bindings into directories by capabilities (and eventually have the data categorized both by vendor and by capability in the root readme -- this sounds like a nice problem to have 😄).

What we start with initially will invariably be restructured a number of times as the quantity of device bindings grows over time.


Here's my quick and dirty proposal on directory structure (assuming the inner directories then contain what @joperezr wrote above):
```
iot/
    src/
        devices/
            audio/
                equalizer/
                midi/
                mp3/
                synthesizer/
            sensors/
                atmospheric/
                biometric/
                distance/
                imaging/
                movement/
                rfid/
            motors/
                servo/
                solenoid/
                stepper/
            displays/
                lcd/
                oled/
                touch/
....
```

**Comment by grahamehorner** [comment]
While all the above makes sence IMHO I believe that the System.Device.xxx shouldn't have anything other than basic implementations and other vendors should support a given type of communication protocol should implementation their driver/controller in a similar manor exposing a common interface that can be built upon. If a vendor/hardware device supports multiple communication protocols then they would implement multiple interfaces by layering accordingly, the results could be a type of nuget packages with special tags that indicate hardware and platforms supported by the package.

**Comment by joperezr** [comment]
@shaggygi I see where it could be confusing for devices that have more than one feature. What about having a markdown dictionary as @joshfree suggests that has both categorizations (by vendor and by capabilities) where the same device can be in more than one capability category? Then, if we go with the model of sorting them by capabilities it should be ok as long as you pick a folder of one of the n capabilities supported by the sensor. The reason why I would still prefer this rather than having it by vendors is that I think there will be more people looking for sensors by capabilities than by vendors.

@grahamehorner I believe what you said above is exactly the plan. This repo contains two different types of libraries: The System.Device.Gpio library (which is the main library that has support for I2C, SPI, GPIO and PWM), and the device binding libraries that will be implemented on top of System.Device.Gpio library. Initially, we only plan to have a NuGet package for System.Device.Gpio library, while we will do source distribution for device binding libraries, but in the future, we might have separate NuGet packages for these as well.

**Comment by shaggygi** [comment]
@joperezr Since we're still in the early stages of bindings, let's go ahead with what @joshfree is promoting and circle back on results.  I guess I can't vision this right now.  Maybe it will click with me after a few binding libraries are made and markdown created.

**Comment by shaggygi** [comment]
Related to sample project names, it seems like there won't always be just one [binding].Sample.csproj.  (hence the folder name samples).  Maybe this could be the default and bare basic example (would probably be the only one in most cases).  However, I can see multiple sample projects for bindings, especially for more complex devices.  Even if we stick with having all different examples (e.g. ReadWithSpi, ReadWithGpio, etc.) within the default sample project and commenting out method calls for flow control, this would allow future growth of binding sample projects.  Each project sample folder would allow for specific assets (e.g. READMEs, Fritzing files, pngs, etc.) to be separated/managed, as well.

For example...

```
iot/
  src/
    devices/
      MyNewBinding/
        MyNewBinding.csproj
        MyNewBinding.cs
        README.md   <-- This should include a fritz diagram of an example
        samples/
            MyNewBinding.Sample    // Folder for default and general use of device.
                MyNewBinding.Sample.csproj
            MyNewBinding.TriggerVoltageBrownoutInterrupt   // Folder for another sample
                MyNewBinding.TriggerVoltageBrownoutInterrupt.csproj
            MyNewBinding.NotifyAzureEventGrid    // Folder for another sample
                MyNewBinding.NotifyAzureEventGrid.csproj
            MyNewBinding.DoSomethingWithDocker    // Folder for another sample
                MyNewBinding.DoSomethingWithDocker.csproj
```

In this case, we would need to move Mcp3008.Sample.csproj sample down into its own folder.
Thoughts?

**Comment by joperezr** [comment]
Personally, I think it's better to only have the one project, which in turn has several different source files (One source file for each sample type). And we could also have multiple samples in one same source file in case they are related. The only reason is so that we don't get that many .csprojs since in theory that will slow the build if we have to call msbuild and the compiler more times than if we just call it one per binding (even if you pass in more than one source file). Restore will also take longer.

**Comment by shaggygi** [comment]
Here is some more categories based on @joshfree thinking.  Not complete.
Used [TI](http://www.ti.com/) and [Microchip](https://www.microchip.com/ParamChartSearch/chart.aspx?branchID=1005) as a reference.

```
 Iot
    Device
        Amplifier
            Comparator
            CurrentSense
            Instrumentation
            Operational
            ProgrammableGain
            PowerSense
            SelectableGain
            SpecialFunction
            VariableGain
        Audio
            
        ClockTiming
            ClockGeneration
            ClockDataDistribution
            Oscillator
            RealTimeClock
        DataConverter
            AnalogToDigital
            DigitalPotentiometer
            DigitalToAnalogConverter
            EnergyMeasurement
            FrequencyToVoltage
            VoltageToFrequency
            VoltageReference
        Interface
            Can
            Infrared
            IoExpander
            Lin
            Usb
        Isolation
        
        Lcd
            
        Logic
            BufferDriver
            FlipFlop
            Gate
            Latch
            Register
            Transceiver
            Specialty
            VoltageLevelTranslation
        Memory
            OtpEeprom
            ParallelEeprom
            SerialEeprom
            SerialEeram
            SerialFlash
            SerialSram
        MotorDriver
            Actuator
            BrushedDc
            BrushlessDc
            OpticalDisk
            Solenoid
            Stepper

        PowerManagement
        
        RfMicrowave
        
        Sensor
            AmbientLight
            Humidity
            Magnetic
            MillimeterWave
            SignalConditioner
            Temperature
            TimeOfFlight
            Ultrasonic
        
        SwitchMultiplexer
        
        Wireless
```

**Comment by krwq** [comment]
I haven't read the whole thread but please note that some devices have more than 1 types of sensors included (i.e. temperature and pressure).

Other example is SenseHat which bundles up sensors and devices together.

What I'd vote to do instead is perhaps add some text file in each directory which would contain 1 line per tag and each tag would be i.e. `thermometer`, `temperature`, `DS18B20`, `1-wire`. We could perhaps create some UI for that so that it is easier to pick tags

That would allow easy searching and allow us to generate some docs/index based on that. However I can think of directories there will be always something which doesn't fit there.

**Comment by shaggygi** [comment]
Yeah, this is a tricky one, but definitely one that we need to think through to be a good maintainable story.  I'm still scratching my head on how to possibly structure 😖 😕

**Comment by krwq** [comment]
tags ftw! 😄

**Comment by krwq** [comment]
@shaggygi now that we have device listing how do you feel about this issue? Do you think we should still change this structure? I still hasn't come up with anything better than we have already so I'm a little bit leaning toward closing this since we don't have any clear plan forward.

**Comment by shaggygi** [comment]
@krwq I think the list should work for now.  Your script seems to do a good job on listing/displaying data.  I'll close for now, but could see the topic arising again as many bindings become available.  Thx

**Comment by krwq** [comment]
agreed, if this becomes a problem again then let's reopen or recreate this issue
