### ISSUE TITLE
Make hardware PWM more responsive

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#638]
Last time I used hardware PWM it had a bit of a lag when changing duty cycle - that made it basically unusable for many real-time scenarios like controlling the vehicle where such lag was causing wheels to turn (i.e. SoftPWM on one wheel reacted faster so effectively it caused vehicle to turn).

This needs to be investigated in 3.0 timeline.

**Comment by joperezr** [comment]
Just a note, the only thing here that is 3.0 is the investigation. If there are any action items out from that, this won't need to happen necessarily for 3.0.
