### ISSUE TITLE
Raspberry Pi not detected using Ubuntu and Debian

### ISSUE THREAD

**Issue by Frankenslag** [dotnet/iot#661]
I believe that I have discovered that the detection logic for determining if a board is a Raspberry Pi only works if running Raspbian and not Ubuntu or Debian.

This is because /proc/cpuinfo doesn't bring back information about the SOC on Debian or Ubuntu.

I believe we should consider improving the detection logic for future releases perhaps using model information from the device tree.

**Comment by joperezr** [comment]
The related conversation for this is: https://github.com/dotnet/iot/pull/595#discussion_r310729445

Changes that were prototyped that would fix this: https://github.com/dotnet/iot/commit/376570188c4871aa05d4e5e71143723bb46a7e65#diff-35260effbe2d55bb01d69655a81939e6R13-R43

```c#
            private const string ModelInfoPath = "/proc/device-tree/model";
            //...            

            // a first chance of finding a raspberry pi..... perhaps not on Raspbian note 
            // that we want this to fail quietly if something goes wrong with the test
            try
            {
                if (File.ReadAllText(ModelInfoPath).StartsWith("Raspberry Pi"))
                {
                    return new RaspberryPi3Driver();
                }
            }
            catch { }
```

**Comment by Frankenslag** [comment]
@joperezr 

Is now the right time to to work on this again ?

**Comment by mjjames** [comment]
I agree, as I have to modify this for my issue #762 I’m happy to do this as part of it just in a separate PR, does it make sense to do so?

**Comment by krwq** [comment]
yes, it's ok, we've only locked 3.0 branch

**Comment by Ellerbach** [comment]
With the documentation added, some changes in the detection logic, and possibility to use a proper driver, I feel this is addressed now. If there is still something specific, feel free to reopen this issue.
