### ISSUE TITLE
Which is the architecture of .NETCore?

### ISSUE THREAD

**Issue by matsujirushi** [dotnet/iot#706]
In [requirements](https://github.com/dotnet/iot/blob/master/samples/README.md#requirements).

1. .NET Core 2.1. .NET Core 3.0 is required for ARM64 devices.
2. .NET Core is supported on Raspberry Pi 2B as well as 3 and 4 models (ARMv7/v8).

Which is the architecture of .NETCore for Raspbian on Raspberry Pi? ARM32 or ARM64?

**Comment by Frankenslag** [comment]
For standard Raspbian it's Arm32

**Comment by krwq** [comment]
.NET Core depends on OS you're using. If you install Ubuntu then ARM64 is also an option but Raspbian (binary) is I believe only ARM32. Source dist might have larger support though and I think there might be a way to make it work on ARM64 but I haven't personally tried.

**Comment by joperezr** [comment]
As @Frankenslag suggests, for most cases you have the regular Raspbian distrubuted on the raspberry pi site, which would be ARM 32. Closing this as the question has been answered. That said, feel free to reopen if you have any follow up questions.
