### ISSUE TITLE
GSM, GPRS, LTE - AT commands

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#725]
One of the common IoT scenarios is to:
- send/receive text message
- answer/make a phone call

We should add support for AT commands - if there is anything device specific we should create also couple of device bindings if not then just create one generic device for that.

PS. Title is just to make it easier to find the issue

**Comment by shaggygi** [comment]
Found this...

https://www.telit.com/wp-content/uploads/2018/01/Telit-LE910-V2-Modules-AT-Commands-Reference-Guide-r3.pdf
-

**Comment by krwq** [comment]
[Triage] We're not tracking the device bindings requests. If anyone is interested in adding support please send a PR

**Comment by krwq** [comment]
There are existing libraries like i.e. https://github.com/hbjorgo/ATLib which can do that.
