### ISSUE TITLE
Re add picking HummingBoard driver when no specific driver is provided

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/iot#76]
HummingBoard driver is not fully implemented yet, so we commented out logic for picking it as default driver, this issue is for tracking the work of re adding that logic back

**Comment by buyaa-n** [comment]
Not sure if we ever gonna add HummingBoard driver implementation, anyways as per https://github.com/dotnet/iot/issues/16 this will not implemented within 3.0, so updating milestone to future

**Comment by krwq** [comment]
[Triage] Closing this because: HummingBoardDriver is almost empty implementation only forwarding to Windows10Driver, we haven't had any complains about it
