### ISSUE TITLE
Sample image has the led pins inverted

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/iot#761]
When I was following these instructions: https://github.com/dotnet/iot/blob/master/samples/led-blink/README.md

I noticed the image is showing the long leg of the led connected to ground, and the short leg connected to pin 17: https://github.com/dotnet/iot/blob/master/samples/led-blink/rpi-led_bb.png

But it should be the other way around.

cc @krwq @joperez

**Comment by krwq** [comment]
good catch @carlossanlop!
