### ISSUE TITLE
Measuring power with GPIO

### ISSUE THREAD

**Issue by MaxMommersteeg** [dotnet/iot#767]
Does dotnet/iot currently support a device binding for measuring power? I'm looking for something that is comparable to INA219. If not I am willing to do some research on how to implement it myself.

**Comment by krwq** [comment]
No, we don't support it at the moment but this device seems to have only 6 registers and uses I2C so I expect adding support should be relatively simple. Please let me know if you need any help.

**Comment by Frankenslag** [comment]
@krwq 
I would be happy to take on the INA219. Would you like to assign me ?

**Comment by krwq** [comment]
Thanks for picking this up @Frankenslag!

**Comment by Frankenslag** [comment]
Closing this as now merged.
