### ISSUE TITLE
Support for MCUs

### ISSUE THREAD

**Issue by ishvedov** [dotnet/iot#81]
Do you have plans to support for MCU like ESP32. Like nanoFramework does?

**Comment by joperezr** [comment]
Initially, our library is targetting .NET Standard which means it will run wherever you can run .NET Standard. Correct me if I'm wrong but looks like ESP32 is more similar to an Arduino, in which it is a single purpose device which won't support any of the frameworks that support .NET Standard which means that it is not in the plans at least for now.

**Comment by ishvedov** [comment]
Thank you, nanoFramework does not support .Net Standard at the moment and the path is not fast.
