### ISSUE TITLE
MFRC522 RFID support

### ISSUE THREAD

**Issue by forki** [dotnet/iot#828]
I'd like to see MFRC522 RFID support 

Currently we call it via INodeServices and https://github.com/firsttris/mfrc522-rpi. But INodeServices is deprecated from asp.net core and so we'd need a replacement.

More info: https://www.nxp.com/docs/en/data-sheet/MFRC522.pdf

**Comment by shaggygi** [comment]
@forki  is this a duplicate of #175?

**Comment by forki** [comment]
Yes thanks. Will subscribe to that one.
