### ISSUE TITLE
TimeEnvelope.IsLastMultiple in example is incorrect.

### ISSUE THREAD

**Issue by kenssamson** [dotnet/iot#884]
**Describe the bug**

**IsLastMultiple** should return true when on last increment of the passed value.  However, it returns false.  The current conditions checks if **_time - value == 0**, this will actually return true on the First Multiple. The condition should be **_count - value == _time**.  

For example, if _count is set to 1000 and value is 200 then IsLastMultiple should return true when _time is 800.   The current logic returns false because  800 - 200 != 0, however, 1000 - 200 == 800.

**Steps to reproduce**

```csharp
var te = new TimeEnvelope(1000);
var multiple = 0;
te.AddTime(100);
while(te.Time != 0)  {
  if (te.IsMultiple(200)) {
     multiple++;
    Console.Writeline($"Multiple Hit {multiple}");
  }   
  if (te.IsFirstMultiple(200)) {
     Console.Writeline("First Multiple Hit");
  }
  if (te.IsLastMultiple(200)) {
    Console.Writeline("Last Multiple Hit");
  }
  te.AddTime(100);
}
```

**Expected behavior**

```
Multiple Hit (1)             // at 200
First Multiple Hit          // at 200
Multiple Hit (2)             // at 400
Multiple Hit (3)             // at 600
Multiple Hit (4)             // at 800 
Last Multiple Hit           // at 800
```

**Actual behavior**

```
Multiple Hit (1)             // at 200
First Multiple Hit          // at 200
Last Multiple Hit           // at 200
Multiple Hit (2)             // at 400
Multiple Hit (3)             // at 600
Multiple Hit (4)             // at 800
```

**Comment by joperezr** [comment]
great catch @kenssamson this indeed looks like a bug in the sample.
