### ISSUE TITLE
porting library with Apache 2.0 license

### ISSUE THREAD

**Issue by garciaolais** [dotnet/iot#921]
Hi

I have a temperature 🌡  sensor [mlx90640 ](https://www.melexis.com/en/product/mlx90640/far-infrared-thermal-sensor-array) and I want to porting this code [melexis-mlx90640-library](https://github.com/melexis/mlx90640-library) but I am not sure if is possible porting code from Apache-2.0 to MIT. 

😕 ❓

**Comment by krwq** [comment]
cc: @richlander

**Comment by krwq** [comment]
@garciaolais any chance this sensor is in any way similar to https://github.com/dotnet/iot/tree/master/src/devices/Mlx90614 ? Possibly some of the code can be re-used. If that's the case it might be easier to compare the registers in the spec

**Comment by joperezr** [comment]
We should use this issue so that once we have an answer for @garciaolais we should document it somewhere in our README. I believe the answer is that we can't take it, but let's wait for @richlander response.

**Comment by krwq** [comment]
I think it actually might be allowed but might require 3rd party notice but I'd prefer @richlander to give official  answer

**Comment by garciaolais** [comment]
Workout 🏋 
![Body](https://user-images.githubusercontent.com/14133711/73904486-da512500-4861-11ea-8bbf-63d718fbafed.gif)


Windows Sample App with multiple temperature palettes 🎨 

![WPF](https://user-images.githubusercontent.com/14133711/73904582-16848580-4862-11ea-88f9-b4974c06f331.jpg)

----------------------------------------------------------------------------------------------------
I'm still working 🚧  on this device 📷 🌡  if someone finds 👀 this thread I can share the sample code. 😃 

PD. The sample is based on code with Apache license.

**Comment by richlander** [comment]
You can port an Apache 2 library to MIT. You just need to an entry to https://github.com/dotnet/iot/blob/master/THIRD-PARTY-NOTICES.TXT.
