### ISSUE TITLE
SoftwarePwmChannel should be in System.Device.Pwm

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#922]
Currently SoftwarePwmChannel exists in System.Device.Pwm.Drivers which is inconsistent with PwmChannel. It should be moved to System.Device.Pwm.

Please let me know what you think before I make any changes

cc: @joperezr @Ellerbach

**Comment by shaggygi** [comment]
Agreed.  I’m assuming this will eventually be moved to the core library (similar to what you previously mentioned about moving the software SPI).  If that is not the intention, it might be worth to go ahead and also rename SoftPwm folder to SoftwarePwm.

**Comment by krwq** [comment]
@shaggygi yes, I hope it will be moved eventually although I think it should pass all our tests first which currently it doesn't (Windows is running against it as fallback).

**Comment by joperezr** [comment]
I agree with @shaggygi and would only do this once we can a) rename this to SoftwarePwm and b) move it down to System.Device.Gpio. That is the right place for it anyway and I think doing these 3 steps separately makes no sense, so lets just do all three together.

**Comment by pgrawehr** [comment]
The name change is no problem at all, but do we really want to move it to System.Device.Gpio? We should keep that library as small as possible IMHO.

**Comment by krwq** [comment]
I'm fine with closing this
