### ISSUE TITLE
DCMotor should have different namespace

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#932]
DCMotor should have namespace which is different than the type name. Having same name causes that in many scenarios it's required to type DCMotor.DCMotor in order to make sure the expression is non-ambigious.

Perhaps DCMotor and Servo should be in the same namespace: `Iot.Device.Motor(s)`

**Comment by pgrawehr** [comment]
Note: Problem exists for other bindings, too (i.e. Ads1115)

**Comment by joperezr** [comment]
This is already the case for most of our bindings, so I believe it would be really hard to change all of them as it would be basically a ginormous breaking change, so I would avoid that unless absolutely necessary.
