### ISSUE TITLE
SoftPwm should be able to pass CI tests on Windows

### ISSUE THREAD

**Issue by krwq** [dotnet/iot#934]
SoftwarePwm implementation is currently failing on Windows. The implementation is platform independent and when I tried it locally on Linux against #758 it was passing all tests (possibly they were flaky - I've tried maybe 3 times). On Windows the values on ADC input (or PWM output after low pass filter) were close to expected value but slightly outside of the expected range. We should try to improve the implementation as much as possible.

I know at minimum room for improvement:
- frequency is slightly lower than the set frequency, i.e. setting freq to 10kHz actually produces around 9.7kHz
- possibly duty cycle is not exactly accurate - we should verify how much off we are and if there is something we can do to improve

As part of this work pwm should be re-enabled on Windows or in simpler words following lines should be removed:
https://github.com/dotnet/iot/pull/758/files#diff-8ac02b215975e2d4379aff2ff01fcf52R49-R50

Note: hardware PWM is currently not supported by default by Windows IoT Core on Raspberry PI (it's possible to do it with external libraries only)

**Comment by pgrawehr** [comment]
We're no longer offically support Windows IoT core on Raspberry PI. We might support Windows 11 on ARM once it's supported on the Pi, but that will require entirely different drivers.
