### ISSUE TITLE
CI Status badge linking to badge image

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/iot#937]
**Describe the bug**

The [CI status badge](https://github.com/dotnet/iot#official-build-status) is linking to the badge itself as opposed to some pipeline.

**Comment by joperezr** [comment]
I believe you are correct, thanks for pointing it out @eiriktsarpalis I'll fix this right away.

**Comment by joperezr** [comment]
Ohh I see what the problem is, the problem is that I linked it to the actual official build status which is internal so only signed in users can see that. I'll switch it to the open rolling build instead.

**Comment by krwq** [comment]
@joperezr now it shows "never built"

**Comment by joperezr** [comment]
Yup, that's expected, continuous integration was disabled on the public build, I enabled that but in order for it to run it needed at least one new commit, which was the one for my readme. So it should be either green/red on a few mins :)
